/* AUTO-GENERATED by tools/gen_shims.py -- DO NOT HAND-EDIT.
 * Regenerate with: python tools/gen_shims.py
 *
 * One logging no-op per SDK symbol not hand-written in
 * platform/null/shims_manual.c / platform/os/*.c -- see this script's own
 * MANUAL_SYMBOLS set for the full list and the per-group reasoning.
 *
 * Used by the --headless build ONLY (tools/build.py) -- every needed
 * symbol gets a shim here, including the ~100+ GX/VI/PAD ones the
 * default (aurora) build instead gets for real from Aurora's own linked
 * libraries (see shims_generated_aurora.c, generated alongside this file,
 * for that build's own variant, and its own header comment for why a
 * SEPARATE file -- not a run-time or weak-symbol distinction -- is what
 * that split needs on this toolchain).
 */
#include "mp6_shim_log.h"
#include "dolphin.h"
#include "dolphin/thp.h"
#include "dolphin/mic.h"
#include "dolphin/m2s.h"
#include "dolphin/demo/DEMOStats.h"
#include "msm.h"

__attribute__((weak)) s32 CARDClose(CARDFileInfo* fileInfo)
{
    MP6_LOG_ONCE("CARD", "CARDClose");
    return (s32)0;
}

__attribute__((weak)) s32 CARDCreate(s32 chan, const char* fileName, u32 size, CARDFileInfo* fileInfo)
{
    MP6_LOG_ONCE("CARD", "CARDCreate");
    return (s32)0;
}

__attribute__((weak)) s32 CARDDelete(s32 chan, const char* fileName)
{
    MP6_LOG_ONCE("CARD", "CARDDelete");
    return (s32)0;
}

__attribute__((weak)) s32 CARDFormat(s32 chan)
{
    MP6_LOG_ONCE("CARD", "CARDFormat");
    return (s32)0;
}

__attribute__((weak)) s32 CARDFreeBlocks(s32 chan, s32* byteNotUsed, s32* filesNotUsed)
{
    MP6_LOG_ONCE("CARD", "CARDFreeBlocks");
    return (s32)0;
}

__attribute__((weak)) s32 CARDGetSerialNo(s32 chan, u64* serialNo)
{
    MP6_LOG_ONCE("CARD", "CARDGetSerialNo");
    return (s32)0;
}

__attribute__((weak)) s32 CARDGetStatus(s32 chan, s32 fileNo, CARDStat* stat)
{
    MP6_LOG_ONCE("CARD", "CARDGetStatus");
    return (s32)0;
}

__attribute__((weak)) void CARDInit(void)
{
    MP6_LOG_ONCE("CARD", "CARDInit");
}

__attribute__((weak)) s32 CARDOpen(s32 chan, const char* fileName, CARDFileInfo* fileInfo)
{
    MP6_LOG_ONCE("CARD", "CARDOpen");
    return (s32)0;
}

__attribute__((weak)) s32 CARDRead(CARDFileInfo* fileInfo, void* addr, s32 length, s32 offset)
{
    MP6_LOG_ONCE("CARD", "CARDRead");
    return (s32)0;
}

__attribute__((weak)) s32 CARDSetStatus(s32 chan, s32 fileNo, CARDStat* stat)
{
    MP6_LOG_ONCE("CARD", "CARDSetStatus");
    return (s32)0;
}

__attribute__((weak)) s32 CARDUnmount(s32 chan)
{
    MP6_LOG_ONCE("CARD", "CARDUnmount");
    return (s32)0;
}

__attribute__((weak)) s32 CARDWrite(CARDFileInfo* fileInfo, const void* addr, s32 length, s32 offset)
{
    MP6_LOG_ONCE("CARD", "CARDWrite");
    return (s32)0;
}

__attribute__((weak)) s32 CARDWriteAsync(CARDFileInfo* fileInfo, const void* addr, s32 length, s32 offset,
                   CARDCallback callback)
{
    MP6_LOG_ONCE("CARD", "CARDWriteAsync");
    return (s32)0;
}

__attribute__((weak)) void C_MTXLightPerspective(Mtx m, f32 fovY, f32 aspect, f32 scaleS, f32 scaleT, f32 transS,
                           f32 transT)
{
    MP6_LOG_ONCE("MTX", "C_MTXLightPerspective");
}

__attribute__((weak)) void C_MTXLookAt(Mtx m, const Point3d* camPos, const Vec* camUp, const Point3d* target)
{
    MP6_LOG_ONCE("MTX", "C_MTXLookAt");
}

__attribute__((weak)) void C_MTXOrtho(Mtx44 m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 f)
{
    MP6_LOG_ONCE("MTX", "C_MTXOrtho");
}

__attribute__((weak)) void C_MTXPerspective(Mtx44 m, f32 fovY, f32 aspect, f32 n, f32 f)
{
    MP6_LOG_ONCE("MTX", "C_MTXPerspective");
}

__attribute__((weak)) void C_VECHalfAngle(const Vec* a, const Vec* b, Vec* half)
{
    MP6_LOG_ONCE("MTX", "C_VECHalfAngle");
}

__attribute__((weak)) void DCFlushRange(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCFlushRange");
}

__attribute__((weak)) void DCFlushRangeNoSync(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCFlushRangeNoSync");
}

__attribute__((weak)) void DCInvalidateRange(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCInvalidateRange");
}

__attribute__((weak)) void DCStoreRange(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCStoreRange");
}

__attribute__((weak)) void DCStoreRangeNoSync(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCStoreRangeNoSync");
}

__attribute__((weak)) void DEMOPrintStats(void)
{
    MP6_LOG_ONCE("DEMO", "DEMOPrintStats");
}

__attribute__((weak)) void DEMOUpdateStats(unsigned char inc)
{
    MP6_LOG_ONCE("DEMO", "DEMOUpdateStats");
}

__attribute__((weak)) void DVDInit(void)
{
    MP6_LOG_ONCE("DVD", "DVDInit");
}

__attribute__((weak)) void GXAbortFrame(void)
{
    MP6_LOG_ONCE("GX", "GXAbortFrame");
}

__attribute__((weak)) void GXAdjustForOverscan(GXRenderModeObj* rmin, GXRenderModeObj* rmout, u16 hor, u16 ver)
{
    MP6_LOG_ONCE("GX", "GXAdjustForOverscan");
}

__attribute__((weak)) void GXClearGPMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearGPMetric");
}

__attribute__((weak)) void GXClearMemMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearMemMetric");
}

__attribute__((weak)) void GXClearPixMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearPixMetric");
}

__attribute__((weak)) void GXClearVCacheMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearVCacheMetric");
}

__attribute__((weak)) void GXClearVtxDesc(void)
{
    MP6_LOG_ONCE("GX", "GXClearVtxDesc");
}

__attribute__((weak)) void GXColor1x16(u16 index)
{
    MP6_LOG_ONCE("GX", "GXColor1x16");
}

__attribute__((weak)) void GXColor1x8(u8 index)
{
    MP6_LOG_ONCE("GX", "GXColor1x8");
}

__attribute__((weak)) void GXColor3u8(u8 r, u8 g, u8 b)
{
    MP6_LOG_ONCE("GX", "GXColor3u8");
}

__attribute__((weak)) void GXColor4u8(u8 r, u8 g, u8 b, u8 a)
{
    MP6_LOG_ONCE("GX", "GXColor4u8");
}

__attribute__((weak)) void GXCopyDisp(void* dest, GXBool clear)
{
    MP6_LOG_ONCE("GX", "GXCopyDisp");
}

__attribute__((weak)) void GXCopyTex(void* dest, GXBool clear)
{
    MP6_LOG_ONCE("GX", "GXCopyTex");
}

__attribute__((weak)) void GXDrawDone(void)
{
    MP6_LOG_ONCE("GX", "GXDrawDone");
}

__attribute__((weak)) u32 GXGetTexBufferSize(u16 width, u16 height, u32 format, GXBool mipmap, u8 max_lod)
{
    MP6_LOG_ONCE("GX", "GXGetTexBufferSize");
    return (u32)0;
}

__attribute__((weak)) f32 GXGetYScaleFactor(u16 efbHeight, u16 xfbHeight)
{
    MP6_LOG_ONCE("GX", "GXGetYScaleFactor");
    return (f32)0;
}

__attribute__((weak)) void GXInitLightAttn(GXLightObj* lt_obj, f32 a0, f32 a1, f32 a2, f32 k0, f32 k1, f32 k2)
{
    MP6_LOG_ONCE("GX", "GXInitLightAttn");
}

__attribute__((weak)) void GXInitLightAttnA(GXLightObj* lt_obj, f32 a0, f32 a1, f32 a2)
{
    MP6_LOG_ONCE("GX", "GXInitLightAttnA");
}

__attribute__((weak)) void GXInitLightColor(GXLightObj* lt_obj, GXColor color)
{
    MP6_LOG_ONCE("GX", "GXInitLightColor");
}

__attribute__((weak)) void GXInitLightDir(GXLightObj* lt_obj, f32 nx, f32 ny, f32 nz)
{
    MP6_LOG_ONCE("GX", "GXInitLightDir");
}

__attribute__((weak)) void GXInitLightDistAttn(GXLightObj* lt_obj, f32 ref_distance, f32 ref_brightness,
                         GXDistAttnFn dist_func)
{
    MP6_LOG_ONCE("GX", "GXInitLightDistAttn");
}

__attribute__((weak)) void GXInitLightPos(GXLightObj* lt_obj, f32 x, f32 y, f32 z)
{
    MP6_LOG_ONCE("GX", "GXInitLightPos");
}

__attribute__((weak)) void GXInitLightSpot(GXLightObj* lt_obj, f32 cutoff, GXSpotFn spot_func)
{
    MP6_LOG_ONCE("GX", "GXInitLightSpot");
}

__attribute__((weak)) void GXInitSpecularDir(GXLightObj* lt_obj, f32 nx, f32 ny, f32 nz)
{
    MP6_LOG_ONCE("GX", "GXInitSpecularDir");
}

__attribute__((weak)) void GXInitTexObj(GXTexObj* obj, void* data, u16 width, u16 height, GXTexFmt format,
                  GXTexWrapMode wrapS, GXTexWrapMode wrapT, u8 mipmap)
{
    MP6_LOG_ONCE("GX", "GXInitTexObj");
}

__attribute__((weak)) void GXInitTexObjCI(GXTexObj* obj, void* data, u16 width, u16 height, GXCITexFmt format,
                    GXTexWrapMode wrapS, GXTexWrapMode wrapT, u8 mipmap, u32 tlut)
{
    MP6_LOG_ONCE("GX", "GXInitTexObjCI");
}

__attribute__((weak)) void GXInitTexObjLOD(GXTexObj* obj, GXTexFilter min_filt, GXTexFilter mag_filt, f32 min_lod,
                     f32 max_lod, f32 lod_bias, GXBool bias_clamp, GXBool do_edge_lod,
                     GXAnisotropy max_aniso)
{
    MP6_LOG_ONCE("GX", "GXInitTexObjLOD");
}

__attribute__((weak)) void GXInitTlutObj(GXTlutObj* obj, void* data, GXTlutFmt format, u16 entries)
{
    MP6_LOG_ONCE("GX", "GXInitTlutObj");
}

__attribute__((weak)) void GXInvalidateTexAll(void)
{
    MP6_LOG_ONCE("GX", "GXInvalidateTexAll");
}

__attribute__((weak)) void GXInvalidateVtxCache(void)
{
    MP6_LOG_ONCE("GX", "GXInvalidateVtxCache");
}

__attribute__((weak)) void GXLoadLightObjImm(const GXLightObj* lt_obj, GXLightID light)
{
    MP6_LOG_ONCE("GX", "GXLoadLightObjImm");
}

__attribute__((weak)) void GXLoadNrmMtxImm(const void* mtx, u32 id)
{
    MP6_LOG_ONCE("GX", "GXLoadNrmMtxImm");
}

__attribute__((weak)) void GXLoadPosMtxImm(const void* mtx, u32 id)
{
    MP6_LOG_ONCE("GX", "GXLoadPosMtxImm");
}

__attribute__((weak)) void GXLoadTexMtxImm(const void* mtx, u32 id, GXTexMtxType type)
{
    MP6_LOG_ONCE("GX", "GXLoadTexMtxImm");
}

__attribute__((weak)) void GXLoadTexObj(GXTexObj* obj, GXTexMapID id)
{
    MP6_LOG_ONCE("GX", "GXLoadTexObj");
}

__attribute__((weak)) void GXLoadTlut(GXTlutObj* obj, u32 idx)
{
    MP6_LOG_ONCE("GX", "GXLoadTlut");
}

__attribute__((weak)) void GXNormal1x16(u16 index)
{
    MP6_LOG_ONCE("GX", "GXNormal1x16");
}

__attribute__((weak)) void GXPixModeSync(void)
{
    MP6_LOG_ONCE("GX", "GXPixModeSync");
}

__attribute__((weak)) void GXPosition1x16(u16 index)
{
    MP6_LOG_ONCE("GX", "GXPosition1x16");
}

__attribute__((weak)) void GXPosition2f32(f32 x, f32 y)
{
    MP6_LOG_ONCE("GX", "GXPosition2f32");
}

__attribute__((weak)) void GXPosition2s16(s16 x, s16 y)
{
    MP6_LOG_ONCE("GX", "GXPosition2s16");
}

__attribute__((weak)) void GXPosition2u16(u16 x, u16 y)
{
    MP6_LOG_ONCE("GX", "GXPosition2u16");
}

__attribute__((weak)) void GXPosition3f32(f32 x, f32 y, f32 z)
{
    MP6_LOG_ONCE("GX", "GXPosition3f32");
}

__attribute__((weak)) void GXPosition3s16(s16 x, s16 y, s16 z)
{
    MP6_LOG_ONCE("GX", "GXPosition3s16");
}

__attribute__((weak)) void GXPosition3u8(u8 x, u8 y, u8 z)
{
    MP6_LOG_ONCE("GX", "GXPosition3u8");
}

__attribute__((weak)) void GXReadGPMetric(u32* count0, u32* count1)
{
    MP6_LOG_ONCE("GX", "GXReadGPMetric");
}

__attribute__((weak)) void GXReadMemMetric(u32* cpReq, u32* tcReq, u32* cpuReadReq, u32* cpuWriteReq, u32* dspReq, u32* ioReq, u32* viReq, u32* peReq,
                            u32* rfReq, u32* fiReq)
{
    MP6_LOG_ONCE("GX", "GXReadMemMetric");
}

__attribute__((weak)) void GXReadPixMetric(u32* topIn, u32* topOut, u32* bottomIn, u32* bottomOut, u32* clearIn, u32* copyClocks)
{
    MP6_LOG_ONCE("GX", "GXReadPixMetric");
}

__attribute__((weak)) void GXReadVCacheMetric(u32* check, u32* miss, u32* stall)
{
    MP6_LOG_ONCE("GX", "GXReadVCacheMetric");
}

__attribute__((weak)) void GXResetWriteGatherPipe(void)
{
    MP6_LOG_ONCE("GX", "GXResetWriteGatherPipe");
}

__attribute__((weak)) void GXSetAlphaCompare(GXCompare comp0, u8 ref0, GXAlphaOp op, GXCompare comp1, u8 ref1)
{
    MP6_LOG_ONCE("GX", "GXSetAlphaCompare");
}

__attribute__((weak)) void GXSetAlphaUpdate(GXBool update_enable)
{
    MP6_LOG_ONCE("GX", "GXSetAlphaUpdate");
}

__attribute__((weak)) void GXSetBlendMode(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor,
                    GXLogicOp op)
{
    MP6_LOG_ONCE("GX", "GXSetBlendMode");
}

__attribute__((weak)) void GXSetChanAmbColor(GXChannelID chan, GXColor amb_color)
{
    MP6_LOG_ONCE("GX", "GXSetChanAmbColor");
}

__attribute__((weak)) void GXSetChanCtrl(GXChannelID chan, GXBool enable, GXColorSrc amb_src, GXColorSrc mat_src,
                   u32 light_mask, GXDiffuseFn diff_fn, GXAttnFn attn_fn)
{
    MP6_LOG_ONCE("GX", "GXSetChanCtrl");
}

__attribute__((weak)) void GXSetChanMatColor(GXChannelID chan, GXColor mat_color)
{
    MP6_LOG_ONCE("GX", "GXSetChanMatColor");
}

__attribute__((weak)) void GXSetColorUpdate(GXBool update_enable)
{
    MP6_LOG_ONCE("GX", "GXSetColorUpdate");
}

__attribute__((weak)) void GXSetCopyClear(GXColor clear_clr, u32 clear_z)
{
    MP6_LOG_ONCE("GX", "GXSetCopyClear");
}

__attribute__((weak)) void GXSetCopyFilter(GXBool aa, u8 sample_pattern[12][2], GXBool vf, u8 vfilter[7])
{
    MP6_LOG_ONCE("GX", "GXSetCopyFilter");
}

__attribute__((weak)) void GXSetCullMode(GXCullMode mode)
{
    MP6_LOG_ONCE("GX", "GXSetCullMode");
}

__attribute__((weak)) void GXSetCurrentMtx(u32 id)
{
    MP6_LOG_ONCE("GX", "GXSetCurrentMtx");
}

__attribute__((weak)) void GXSetDispCopyDst(u16 wd, u16 ht)
{
    MP6_LOG_ONCE("GX", "GXSetDispCopyDst");
}

__attribute__((weak)) void GXSetDispCopyGamma(GXGamma gamma)
{
    MP6_LOG_ONCE("GX", "GXSetDispCopyGamma");
}

__attribute__((weak)) void GXSetDispCopySrc(u16 left, u16 top, u16 wd, u16 ht)
{
    MP6_LOG_ONCE("GX", "GXSetDispCopySrc");
}

__attribute__((weak)) u32 GXSetDispCopyYScale(f32 vscale)
{
    MP6_LOG_ONCE("GX", "GXSetDispCopyYScale");
    return (u32)0;
}

__attribute__((weak)) void GXSetDrawDone(void)
{
    MP6_LOG_ONCE("GX", "GXSetDrawDone");
}

__attribute__((weak)) void GXSetDrawSync(u16 token)
{
    MP6_LOG_ONCE("GX", "GXSetDrawSync");
}

__attribute__((weak)) GXDrawSyncCallback GXSetDrawSyncCallback(GXDrawSyncCallback callback)
{
    MP6_LOG_ONCE("GX", "GXSetDrawSyncCallback");
    return (GXDrawSyncCallback)0;
}

__attribute__((weak)) void GXSetFog(GXFogType type, f32 startz, f32 endz, f32 nearz, f32 farz, GXColor color)
{
    MP6_LOG_ONCE("GX", "GXSetFog");
}

__attribute__((weak)) void GXSetIndTexCoordScale(GXIndTexStageID ind_state, GXIndTexScale scale_s, GXIndTexScale scale_t)
{
    MP6_LOG_ONCE("GX", "GXSetIndTexCoordScale");
}

__attribute__((weak)) void GXSetIndTexMtx(GXIndTexMtxID mtx_sel, const void* offset, s8 scale_exp)
{
    MP6_LOG_ONCE("GX", "GXSetIndTexMtx");
}

__attribute__((weak)) void GXSetIndTexOrder(GXIndTexStageID ind_stage, GXTexCoordID tex_coord, GXTexMapID tex_map)
{
    MP6_LOG_ONCE("GX", "GXSetIndTexOrder");
}

__attribute__((weak)) void GXSetNumChans(u8 nChans)
{
    MP6_LOG_ONCE("GX", "GXSetNumChans");
}

__attribute__((weak)) void GXSetNumIndStages(u8 nIndStages)
{
    MP6_LOG_ONCE("GX", "GXSetNumIndStages");
}

__attribute__((weak)) void GXSetNumTevStages(u8 nStages)
{
    MP6_LOG_ONCE("GX", "GXSetNumTevStages");
}

__attribute__((weak)) void GXSetNumTexGens(u8 nTexGens)
{
    MP6_LOG_ONCE("GX", "GXSetNumTexGens");
}

__attribute__((weak)) void GXSetPixelFmt(GXPixelFmt pix_fmt, GXZFmt16 z_fmt)
{
    MP6_LOG_ONCE("GX", "GXSetPixelFmt");
}

__attribute__((weak)) void GXSetProjection(const void* mtx, GXProjectionType type)
{
    MP6_LOG_ONCE("GX", "GXSetProjection");
}

__attribute__((weak)) void GXSetScissor(u32 left, u32 top, u32 wd, u32 ht)
{
    MP6_LOG_ONCE("GX", "GXSetScissor");
}

__attribute__((weak)) void GXSetTevAlphaIn(GXTevStageID stage, GXTevAlphaArg a, GXTevAlphaArg b, GXTevAlphaArg c,
                     GXTevAlphaArg d)
{
    MP6_LOG_ONCE("GX", "GXSetTevAlphaIn");
}

__attribute__((weak)) void GXSetTevAlphaOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp,
                     GXTevRegID out_reg)
{
    MP6_LOG_ONCE("GX", "GXSetTevAlphaOp");
}

__attribute__((weak)) void GXSetTevColor(GXTevRegID id, GXColor color)
{
    MP6_LOG_ONCE("GX", "GXSetTevColor");
}

__attribute__((weak)) void GXSetTevColorIn(GXTevStageID stage, GXTevColorArg a, GXTevColorArg b, GXTevColorArg c,
                     GXTevColorArg d)
{
    MP6_LOG_ONCE("GX", "GXSetTevColorIn");
}

__attribute__((weak)) void GXSetTevColorOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp,
                     GXTevRegID out_reg)
{
    MP6_LOG_ONCE("GX", "GXSetTevColorOp");
}

__attribute__((weak)) void GXSetTevColorS10(GXTevRegID id, GXColorS10 color)
{
    MP6_LOG_ONCE("GX", "GXSetTevColorS10");
}

__attribute__((weak)) void GXSetTevDirect(GXTevStageID tev_stage)
{
    MP6_LOG_ONCE("GX", "GXSetTevDirect");
}

__attribute__((weak)) void GXSetTevIndTile(GXTevStageID tev_stage, GXIndTexStageID ind_stage,
        u16 tilesize_s, u16 tilesize_t,
        u16 tilespacing_s, u16 tilespacing_t,
        GXIndTexFormat format, GXIndTexMtxID matrix_sel,
        GXIndTexBiasSel bias_sel, GXIndTexAlphaSel alpha_sel)
{
    MP6_LOG_ONCE("GX", "GXSetTevIndTile");
}

__attribute__((weak)) void GXSetTevIndWarp(GXTevStageID tev_stage, GXIndTexStageID ind_stage, GXBool signed_offsets,
                     GXBool replace_mode, GXIndTexMtxID matrix_sel)
{
    MP6_LOG_ONCE("GX", "GXSetTevIndWarp");
}

__attribute__((weak)) void GXSetTevKAlphaSel(GXTevStageID stage, GXTevKAlphaSel sel)
{
    MP6_LOG_ONCE("GX", "GXSetTevKAlphaSel");
}

__attribute__((weak)) void GXSetTevKColor(GXTevKColorID id, GXColor color)
{
    MP6_LOG_ONCE("GX", "GXSetTevKColor");
}

__attribute__((weak)) void GXSetTevKColorSel(GXTevStageID stage, GXTevKColorSel sel)
{
    MP6_LOG_ONCE("GX", "GXSetTevKColorSel");
}

__attribute__((weak)) void GXSetTevOp(GXTevStageID id, GXTevMode mode)
{
    MP6_LOG_ONCE("GX", "GXSetTevOp");
}

__attribute__((weak)) void GXSetTevOrder(GXTevStageID stage, GXTexCoordID coord, GXTexMapID map, GXChannelID color)
{
    MP6_LOG_ONCE("GX", "GXSetTevOrder");
}

__attribute__((weak)) void GXSetTevSwapMode(GXTevStageID stage, GXTevSwapSel ras_sel, GXTevSwapSel tex_sel)
{
    MP6_LOG_ONCE("GX", "GXSetTevSwapMode");
}

__attribute__((weak)) void GXSetTevSwapModeTable(GXTevSwapSel table, GXTevColorChan red, GXTevColorChan green,
                           GXTevColorChan blue, GXTevColorChan alpha)
{
    MP6_LOG_ONCE("GX", "GXSetTevSwapModeTable");
}

__attribute__((weak)) void GXSetTexCoordGen2(GXTexCoordID dst_coord, GXTexGenType func, GXTexGenSrc src_param, u32 mtx,
                       GXBool normalize, u32 postmtx)
{
    MP6_LOG_ONCE("GX", "GXSetTexCoordGen2");
}

__attribute__((weak)) void GXSetTexCoordScaleManually(GXTexCoordID coord, GXBool enable, u16 ss, u16 ts)
{
    MP6_LOG_ONCE("GX", "GXSetTexCoordScaleManually");
}

__attribute__((weak)) void GXSetTexCopyDst(u16 wd, u16 ht, GXTexFmt fmt, GXBool mipmap)
{
    MP6_LOG_ONCE("GX", "GXSetTexCopyDst");
}

__attribute__((weak)) void GXSetTexCopySrc(u16 left, u16 top, u16 wd, u16 ht)
{
    MP6_LOG_ONCE("GX", "GXSetTexCopySrc");
}

__attribute__((weak)) void GXSetViewport(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz)
{
    MP6_LOG_ONCE("GX", "GXSetViewport");
}

__attribute__((weak)) void GXSetViewportJitter(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz, u32 field)
{
    MP6_LOG_ONCE("GX", "GXSetViewportJitter");
}

__attribute__((weak)) void GXSetVtxAttrFmt(GXVtxFmt vtxfmt, GXAttr attr, GXCompCnt cnt, GXCompType type, u8 frac)
{
    MP6_LOG_ONCE("GX", "GXSetVtxAttrFmt");
}

__attribute__((weak)) void GXSetVtxDesc(GXAttr attr, GXAttrType type)
{
    MP6_LOG_ONCE("GX", "GXSetVtxDesc");
}

__attribute__((weak)) void GXSetZCompLoc(GXBool before_tex)
{
    MP6_LOG_ONCE("GX", "GXSetZCompLoc");
}

__attribute__((weak)) void GXSetZMode(GXBool compare_enable, GXCompare func, GXBool update_enable)
{
    MP6_LOG_ONCE("GX", "GXSetZMode");
}

__attribute__((weak)) void GXTexCoord1x16(u16 index)
{
    MP6_LOG_ONCE("GX", "GXTexCoord1x16");
}

__attribute__((weak)) void GXTexCoord2f32(f32 s, f32 t)
{
    MP6_LOG_ONCE("GX", "GXTexCoord2f32");
}

__attribute__((weak)) void GXTexCoord2s16(s16 s, s16 t)
{
    MP6_LOG_ONCE("GX", "GXTexCoord2s16");
}

__attribute__((weak)) void GXWaitDrawDone(void)
{
    MP6_LOG_ONCE("GX", "GXWaitDrawDone");
}

__attribute__((weak)) void LCDisable(void)
{
    MP6_LOG_ONCE("LC", "LCDisable");
}

__attribute__((weak)) void LCEnable(void)
{
    MP6_LOG_ONCE("LC", "LCEnable");
}

__attribute__((weak)) void M2SAdvanceBuffer(s32 samples)
{
    MP6_LOG_ONCE("M2S", "M2SAdvanceBuffer");
}

__attribute__((weak)) void M2SClose(void)
{
    MP6_LOG_ONCE("M2S", "M2SClose");
}

__attribute__((weak)) s32 M2SGetSamples(s16** buffer, s32 samples)
{
    MP6_LOG_ONCE("M2S", "M2SGetSamples");
    return (s32)0;
}

__attribute__((weak)) s32 M2SGetSamplesLeft(void)
{
    MP6_LOG_ONCE("M2S", "M2SGetSamplesLeft");
    return (s32)0;
}

__attribute__((weak)) void M2SInit(void)
{
    MP6_LOG_ONCE("M2S", "M2SInit");
}

__attribute__((weak)) void M2SOpen(void)
{
    MP6_LOG_ONCE("M2S", "M2SOpen");
}

__attribute__((weak)) BOOL M2SSetActiveChannel(s32 chan)
{
    MP6_LOG_ONCE("M2S", "M2SSetActiveChannel");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetBuffer(s16* buffer)
{
    MP6_LOG_ONCE("M2S", "M2SSetBuffer");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetMode(s32 mode)
{
    MP6_LOG_ONCE("M2S", "M2SSetMode");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetPrerecordSamples(s32 milliseconds)
{
    MP6_LOG_ONCE("M2S", "M2SSetPrerecordSamples");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetShifts(s32 shifts)
{
    MP6_LOG_ONCE("M2S", "M2SSetShifts");
    return (BOOL)1;
}

__attribute__((weak)) void M2SStart(void)
{
    MP6_LOG_ONCE("M2S", "M2SStart");
}

__attribute__((weak)) void M2SStop(void)
{
    MP6_LOG_ONCE("M2S", "M2SStop");
}

__attribute__((weak)) s32 MICGetButton(s32 chan, u32* button)
{
    MP6_LOG_ONCE("MIC", "MICGetButton");
    return (s32)0;
}

__attribute__((weak)) s32 MICGetDeviceID(s32 chan, u32* id)
{
    MP6_LOG_ONCE("MIC", "MICGetDeviceID");
    return (s32)0;
}

__attribute__((weak)) s32 MICGetSamples(s32 chan, s16* buffer, s32 index, s32 samples)
{
    MP6_LOG_ONCE("MIC", "MICGetSamples");
    return (s32)0;
}

__attribute__((weak)) s32 MICGetSamplesLeft(s32 chan, s32 index)
{
    MP6_LOG_ONCE("MIC", "MICGetSamplesLeft");
    return (s32)0;
}

__attribute__((weak)) void MICInit(void)
{
    MP6_LOG_ONCE("MIC", "MICInit");
}

__attribute__((weak)) BOOL MICIsActive(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICIsActive");
    return (BOOL)1;
}

__attribute__((weak)) s32 MICSetGain(s32 chan, s32 gain)
{
    MP6_LOG_ONCE("MIC", "MICSetGain");
    return (s32)0;
}

__attribute__((weak)) s32 MICStart(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICStart");
    return (s32)0;
}

__attribute__((weak)) s32 MICStop(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICStop");
    return (s32)0;
}

__attribute__((weak)) s32 MICUnmount(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICUnmount");
    return (s32)0;
}

__attribute__((weak)) s32 MICUpdateIndex(s32 chan, s32 index, s32 samples)
{
    MP6_LOG_ONCE("MIC", "MICUpdateIndex");
    return (s32)0;
}

__attribute__((weak)) void OSCancelThread(OSThread* thread)
{
    MP6_LOG_ONCE("OS", "OSCancelThread");
}

__attribute__((weak)) OSTime OSCheckStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSCheckStopwatch");
    return (OSTime)0;
}

__attribute__((weak)) void OSCreateAlarm(OSAlarm* alarm)
{
    MP6_LOG_ONCE("OS", "OSCreateAlarm");
}

__attribute__((weak)) BOOL OSCreateThread(OSThread* thread, void* (*func)(void*), void* param, void* stack, u32 stackSize,
                    OSPriority priority, u16 attr)
{
    MP6_LOG_ONCE("OS", "OSCreateThread");
    return (BOOL)1;
}

__attribute__((weak)) BOOL OSDisableInterrupts(void)
{
    MP6_LOG_ONCE("OS", "OSDisableInterrupts");
    return (BOOL)1;
}

__attribute__((weak)) BOOL OSEnableInterrupts(void)
{
    MP6_LOG_ONCE("OS", "OSEnableInterrupts");
    return (BOOL)1;
}

__attribute__((weak)) u32 OSGetConsoleSimulatedMemSize(void)
{
    MP6_LOG_ONCE("OS", "OSGetConsoleSimulatedMemSize");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetConsoleType(void)
{
    MP6_LOG_ONCE("OS", "OSGetConsoleType");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetPhysicalMemSize(void)
{
    MP6_LOG_ONCE("OS", "OSGetPhysicalMemSize");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetProgressiveMode(void)
{
    MP6_LOG_ONCE("OS", "OSGetProgressiveMode");
    return (u32)0;
}

__attribute__((weak)) BOOL OSGetResetButtonState(void)
{
    MP6_LOG_ONCE("OS", "OSGetResetButtonState");
    return (BOOL)1;
}

__attribute__((weak)) u32 OSGetResetCode(void)
{
    MP6_LOG_ONCE("OS", "OSGetResetCode");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetSoundMode(void)
{
    MP6_LOG_ONCE("OS", "OSGetSoundMode");
    return (u32)0;
}

__attribute__((weak)) void OSInit(void)
{
    MP6_LOG_ONCE("OS", "OSInit");
}

__attribute__((weak)) void OSInitMessageQueue(OSMessageQueue* mq, OSMessage* msgArray, s32 msgCount)
{
    MP6_LOG_ONCE("OS", "OSInitMessageQueue");
}

__attribute__((weak)) void OSInitStopwatch(OSStopwatch* sw, char* name)
{
    MP6_LOG_ONCE("OS", "OSInitStopwatch");
}

__attribute__((weak)) void OSInitThreadQueue(OSThreadQueue* queue)
{
    MP6_LOG_ONCE("OS", "OSInitThreadQueue");
}

__attribute__((weak)) BOOL OSReceiveMessage(OSMessageQueue* mq, OSMessage* msg, s32 flags)
{
    MP6_LOG_ONCE("OS", "OSReceiveMessage");
    return (BOOL)1;
}

__attribute__((weak)) void OSResetStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSResetStopwatch");
}

__attribute__((weak)) void OSResetSystem(s32 reset, u32 resetCode, BOOL forceMenu)
{
    MP6_LOG_ONCE("OS", "OSResetSystem");
}

__attribute__((weak)) BOOL OSRestoreInterrupts(BOOL level)
{
    MP6_LOG_ONCE("OS", "OSRestoreInterrupts");
    return (BOOL)1;
}

__attribute__((weak)) s32 OSResumeThread(OSThread* thread)
{
    MP6_LOG_ONCE("OS", "OSResumeThread");
    return (s32)0;
}

__attribute__((weak)) BOOL OSSendMessage(OSMessageQueue* mq, OSMessage msg, s32 flags)
{
    MP6_LOG_ONCE("OS", "OSSendMessage");
    return (BOOL)1;
}

__attribute__((weak)) void OSSetAlarm(OSAlarm* alarm, OSTime tick, OSAlarmHandler handler)
{
    MP6_LOG_ONCE("OS", "OSSetAlarm");
}

__attribute__((weak)) OSErrorHandler OSSetErrorHandler(OSError code, OSErrorHandler handler)
{
    MP6_LOG_ONCE("OS", "OSSetErrorHandler");
    return (OSErrorHandler)0;
}

__attribute__((weak)) OSThread* OSSetIdleFunction(OSIdleFunction idleFunction, void* param, void* stack, u32 stackSize)
{
    MP6_LOG_ONCE("OS", "OSSetIdleFunction");
    return (OSThread*)0;
}

__attribute__((weak)) void OSSetProgressiveMode(u32 on)
{
    MP6_LOG_ONCE("OS", "OSSetProgressiveMode");
}

__attribute__((weak)) BOOL OSSetThreadPriority(OSThread* thread, OSPriority priority)
{
    MP6_LOG_ONCE("OS", "OSSetThreadPriority");
    return (BOOL)1;
}

__attribute__((weak)) void OSSleepThread(OSThreadQueue* queue)
{
    MP6_LOG_ONCE("OS", "OSSleepThread");
}

__attribute__((weak)) void OSStartStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSStartStopwatch");
}

__attribute__((weak)) void OSStopStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSStopStopwatch");
}

__attribute__((weak)) s32 OSSuspendThread(OSThread* thread)
{
    MP6_LOG_ONCE("OS", "OSSuspendThread");
    return (s32)0;
}

__attribute__((weak)) void OSWakeupThread(OSThreadQueue* queue)
{
    MP6_LOG_ONCE("OS", "OSWakeupThread");
}

__attribute__((weak)) void OSYieldThread(void)
{
    MP6_LOG_ONCE("OS", "OSYieldThread");
}

__attribute__((weak)) void PADClampCircle(PADStatus* status)
{
    MP6_LOG_ONCE("PAD", "PADClampCircle");
}

__attribute__((weak)) void PADControlMotor(s32 chan, u32 cmd)
{
    MP6_LOG_ONCE("PAD", "PADControlMotor");
}

__attribute__((weak)) BOOL PADInit(void)
{
    MP6_LOG_ONCE("PAD", "PADInit");
    return (BOOL)1;
}

__attribute__((weak)) u32 PADRead(PADStatus* status)
{
    MP6_LOG_ONCE("PAD", "PADRead");
    return (u32)0;
}

__attribute__((weak)) BOOL PADRecalibrate(u32 mask)
{
    MP6_LOG_ONCE("PAD", "PADRecalibrate");
    return (BOOL)1;
}

__attribute__((weak)) BOOL PADReset(u32 mask)
{
    MP6_LOG_ONCE("PAD", "PADReset");
    return (BOOL)1;
}

__attribute__((weak)) void PADSetSpec(u32 spec)
{
    MP6_LOG_ONCE("PAD", "PADSetSpec");
}

__attribute__((weak)) void PPCSync(void)
{
    MP6_LOG_ONCE("CACHE", "PPCSync");
}

__attribute__((weak)) void PSMTXConcat(const Mtx a, const Mtx b, Mtx ab)
{
    MP6_LOG_ONCE("MTX", "PSMTXConcat");
}

__attribute__((weak)) void PSMTXCopy(const Mtx src, Mtx dst)
{
    MP6_LOG_ONCE("MTX", "PSMTXCopy");
}

__attribute__((weak)) void PSMTXIdentity(Mtx m)
{
    MP6_LOG_ONCE("MTX", "PSMTXIdentity");
}

__attribute__((weak)) u32 PSMTXInvXpose(const Mtx src, Mtx invX)
{
    MP6_LOG_ONCE("MTX", "PSMTXInvXpose");
    return (u32)0;
}

__attribute__((weak)) u32 PSMTXInverse(const Mtx src, Mtx inv)
{
    MP6_LOG_ONCE("MTX", "PSMTXInverse");
    return (u32)0;
}

__attribute__((weak)) void PSMTXMultVec(const Mtx m, const Vec* src, Vec* dst)
{
    MP6_LOG_ONCE("MTX", "PSMTXMultVec");
}

__attribute__((weak)) void PSMTXMultVecArray(const Mtx m, const Vec* srcBase, Vec* dstBase, u32 count)
{
    MP6_LOG_ONCE("MTX", "PSMTXMultVecArray");
}

__attribute__((weak)) void PSMTXMultVecSR(const Mtx m, const Vec* src, Vec* dst)
{
    MP6_LOG_ONCE("MTX", "PSMTXMultVecSR");
}

__attribute__((weak)) void PSMTXROMultVecArray(const ROMtx m, const Vec* srcBase, Vec* dstBase, u32 count)
{
    MP6_LOG_ONCE("MTX", "PSMTXROMultVecArray");
}

__attribute__((weak)) void PSMTXReorder(const Mtx src, ROMtx dest)
{
    MP6_LOG_ONCE("MTX", "PSMTXReorder");
}

__attribute__((weak)) void PSMTXRotAxisRad(Mtx m, const Vec* axis, f32 rad)
{
    MP6_LOG_ONCE("MTX", "PSMTXRotAxisRad");
}

__attribute__((weak)) void PSMTXRotRad(Mtx m, char axis, f32 rad)
{
    MP6_LOG_ONCE("MTX", "PSMTXRotRad");
}

__attribute__((weak)) void PSMTXScale(Mtx m, f32 xS, f32 yS, f32 zS)
{
    MP6_LOG_ONCE("MTX", "PSMTXScale");
}

__attribute__((weak)) void PSMTXTrans(Mtx m, f32 xT, f32 yT, f32 zT)
{
    MP6_LOG_ONCE("MTX", "PSMTXTrans");
}

__attribute__((weak)) void PSVECAdd(const Vec* a, const Vec* b, Vec* ab)
{
    MP6_LOG_ONCE("MTX", "PSVECAdd");
}

__attribute__((weak)) void PSVECCrossProduct(const Vec* a, const Vec* b, Vec* axb)
{
    MP6_LOG_ONCE("MTX", "PSVECCrossProduct");
}

__attribute__((weak)) f32 PSVECDistance(const Vec* a, const Vec* b)
{
    MP6_LOG_ONCE("MTX", "PSVECDistance");
    return (f32)0;
}

__attribute__((weak)) f32 PSVECDotProduct(const Vec* a, const Vec* b)
{
    MP6_LOG_ONCE("MTX", "PSVECDotProduct");
    return (f32)0;
}

__attribute__((weak)) f32 PSVECMag(const Vec* v)
{
    MP6_LOG_ONCE("MTX", "PSVECMag");
    return (f32)0;
}

__attribute__((weak)) void PSVECNormalize(const Vec* src, Vec* unit)
{
    MP6_LOG_ONCE("MTX", "PSVECNormalize");
}

__attribute__((weak)) void PSVECScale(const Vec* src, Vec* dst, f32 scale)
{
    MP6_LOG_ONCE("MTX", "PSVECScale");
}

__attribute__((weak)) f32 PSVECSquareMag(const Vec* v)
{
    MP6_LOG_ONCE("MTX", "PSVECSquareMag");
    return (f32)0;
}

__attribute__((weak)) void PSVECSubtract(const Vec* a, const Vec* b, Vec* a_b)
{
    MP6_LOG_ONCE("MTX", "PSVECSubtract");
}

__attribute__((weak)) u32 SIProbe(s32 chan)
{
    MP6_LOG_ONCE("SI", "SIProbe");
    return (u32)0;
}

__attribute__((weak)) void SISetSamplingRate(u32 msec)
{
    MP6_LOG_ONCE("SI", "SISetSamplingRate");
}

__attribute__((weak)) u32 THPAudioDecode(s16* audioBuffer, u8* audioFrame, s32 flag)
{
    MP6_LOG_ONCE("THP", "THPAudioDecode");
    return (u32)0;
}

__attribute__((weak)) s32 THPVideoDecode(void* file, void* tileY, void* tileU, void* tileV, void* work)
{
    MP6_LOG_ONCE("THP", "THPVideoDecode");
    return (s32)0;
}

__attribute__((weak)) void VIConfigure(const GXRenderModeObj* rm)
{
    MP6_LOG_ONCE("VI", "VIConfigure");
}

__attribute__((weak)) void VIConfigurePan(u16 xOrg, u16 yOrg, u16 width, u16 height)
{
    MP6_LOG_ONCE("VI", "VIConfigurePan");
}

__attribute__((weak)) void VIFlush(void)
{
    MP6_LOG_ONCE("VI", "VIFlush");
}

__attribute__((weak)) u32 VIGetDTVStatus(void)
{
    MP6_LOG_ONCE("VI", "VIGetDTVStatus");
    return (u32)0;
}

__attribute__((weak)) u32 VIGetTvFormat(void)
{
    MP6_LOG_ONCE("VI", "VIGetTvFormat");
    return (u32)0;
}

__attribute__((weak)) void VISetBlack(BOOL black)
{
    MP6_LOG_ONCE("VI", "VISetBlack");
}

__attribute__((weak)) void VISetNextFrameBuffer(void* fb)
{
    MP6_LOG_ONCE("VI", "VISetNextFrameBuffer");
}

__attribute__((weak)) VIRetraceCallback VISetPostRetraceCallback(VIRetraceCallback callback)
{
    MP6_LOG_ONCE("VI", "VISetPostRetraceCallback");
    return (VIRetraceCallback)0;
}

__attribute__((weak)) VIRetraceCallback VISetPreRetraceCallback(VIRetraceCallback callback)
{
    MP6_LOG_ONCE("VI", "VISetPreRetraceCallback");
    return (VIRetraceCallback)0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_Close; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_Close()
{
    MP6_LOG_ONCE("OS", "gsapi_Close");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextActivate; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextActivate()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextActivate");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextDeActivate; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextDeActivate()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextDeActivate");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetCtxData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetCtxData()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetCtxData");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetGcdData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetGcdData()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetGcdData");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetParam; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetParam()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetParam");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetWrdData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetWrdData()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetWrdData");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineClose; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineClose()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineClose");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineOpen; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineOpen()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineOpen");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineRestart; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineRestart()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineRestart");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSessionDataExport; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSessionDataExport()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSessionDataExport");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSessionDataFree; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSessionDataFree()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSessionDataFree");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSessionDataImport; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSessionDataImport()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSessionDataImport");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSetMode; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSetMode()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSetMode");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSetParam; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSetParam()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSetParam");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineStart; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineStart()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineStart");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineStop; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineStop()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineStop");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_Init; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_Init()
{
    MP6_LOG_ONCE("OS", "gsapi_Init");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_LanguageLoadBuffer; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_LanguageLoadBuffer()
{
    MP6_LOG_ONCE("OS", "gsapi_LanguageLoadBuffer");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_LanguageUnLoad; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_LanguageUnLoad()
{
    MP6_LOG_ONCE("OS", "gsapi_LanguageUnLoad");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_NotifySetCallback; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_NotifySetCallback()
{
    MP6_LOG_ONCE("OS", "gsapi_NotifySetCallback");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_SetUserData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_SetUserData()
{
    MP6_LOG_ONCE("OS", "gsapi_SetUserData");
    return 0;
}

__attribute__((weak)) void mp6_GXBegin(GXPrimitive type, GXVtxFmt vtxfmt, u16 nverts)
{
    MP6_LOG_ONCE("GX", "mp6_GXBegin");
}

__attribute__((weak)) void mp6_GXBeginDisplayList(void* list, u32 size)
{
    MP6_LOG_ONCE("GX", "mp6_GXBeginDisplayList");
}

__attribute__((weak)) void mp6_GXCallDisplayList(const void* list, u32 nbytes)
{
    MP6_LOG_ONCE("GX", "mp6_GXCallDisplayList");
}

__attribute__((weak)) void mp6_GXEnd(void)
{
    MP6_LOG_ONCE("GX", "mp6_GXEnd");
}

__attribute__((weak)) u32 mp6_GXEndDisplayList(void)
{
    MP6_LOG_ONCE("GX", "mp6_GXEndDisplayList");
    return (u32)0;
}

__attribute__((weak)) void mp6_GXSetArray3(GXAttr attr, void* data, u8 stride)
{
    MP6_LOG_ONCE("GX", "mp6_GXSetArray3");
}

__attribute__((weak)) void msmMusFdoutEnd(void)
{
    MP6_LOG_ONCE("MSM", "msmMusFdoutEnd");
}

__attribute__((weak)) s32 msmMusGetMidiCtrl(int musNo, s32 channel, s32 ctrl)
{
    MP6_LOG_ONCE("MSM", "msmMusGetMidiCtrl");
    return (s32)0;
}

__attribute__((weak)) s32 msmMusGetNumPlay(BOOL baseGrp)
{
    MP6_LOG_ONCE("MSM", "msmMusGetNumPlay");
    return (s32)0;
}

__attribute__((weak)) s32 msmMusGetStatus(int musNo)
{
    MP6_LOG_ONCE("MSM", "msmMusGetStatus");
    return (s32)0;
}

__attribute__((weak)) s32 msmMusPauseAll(BOOL pause, s32 speed)
{
    MP6_LOG_ONCE("MSM", "msmMusPauseAll");
    return (s32)0;
}

__attribute__((weak)) int msmMusPlay(int musId, MSM_MUSPARAM *musParam)
{
    MP6_LOG_ONCE("MSM", "msmMusPlay");
    return (int)0;
}

__attribute__((weak)) void msmMusSetMasterVolume(int volume)
{
    MP6_LOG_ONCE("MSM", "msmMusSetMasterVolume");
}

__attribute__((weak)) s32 msmMusStop(int musNo, s32 speed)
{
    MP6_LOG_ONCE("MSM", "msmMusStop");
    return (s32)0;
}

__attribute__((weak)) void msmMusStopAll(BOOL checkGrp, s32 speed)
{
    MP6_LOG_ONCE("MSM", "msmMusStopAll");
}

__attribute__((weak)) void msmSeDelListener(void)
{
    MP6_LOG_ONCE("MSM", "msmSeDelListener");
}

__attribute__((weak)) s32 msmSeGetEntryID(s16 seId, int *seNo)
{
    MP6_LOG_ONCE("MSM", "msmSeGetEntryID");
    return (s32)0;
}

__attribute__((weak)) MSMSE * msmSeGetIndexPtr(s32 seId)
{
    MP6_LOG_ONCE("MSM", "msmSeGetIndexPtr");
    return (MSMSE *)0;
}

__attribute__((weak)) s32 msmSeGetNumPlay(BOOL baseGrp)
{
    MP6_LOG_ONCE("MSM", "msmSeGetNumPlay");
    return (s32)0;
}

__attribute__((weak)) s32 msmSeSetListener(Vec *pos, Vec *heading, float sndDist, float sndSpeed, MSM_SELISTENER *listener)
{
    MP6_LOG_ONCE("MSM", "msmSeSetListener");
    return (s32)0;
}

__attribute__((weak)) s32 msmSeUpdataListener(Vec *pos, Vec *heading)
{
    MP6_LOG_ONCE("MSM", "msmSeUpdataListener");
    return (s32)0;
}

__attribute__((weak)) void msmSysCheckInit(void)
{
    MP6_LOG_ONCE("MSM", "msmSysCheckInit");
}

__attribute__((weak)) s32 msmSysSetAux(s32 auxA, s32 auxB)
{
    MP6_LOG_ONCE("MSM", "msmSysSetAux");
    return (s32)0;
}

__attribute__((weak)) void msmSysSetOutputMode(SND_OUTPUTMODE mode)
{
    MP6_LOG_ONCE("MSM", "msmSysSetOutputMode");
}
