/* AUTO-GENERATED by tools/gen_shims.py -- DO NOT HAND-EDIT.
 * Regenerate with: python tools/gen_shims.py
 *
 * Used by the DEFAULT (aurora) build ONLY -- see OUT_FILE_AURORA's own
 * comment in gen_shims.py for the full story of why this file excludes
 * every symbol aurora_surface.json's 'implemented' inventory says Aurora
 * provides a real, linkable definition for (confirmed empirically:
 * generating a shim for these, even a weak one, silently prevents
 * Aurora's own real implementation from ever being linked in at all --
 * COFF/lld-link's weak-external resolution never triggers archive
 * extraction on its own). Everything else -- the true GX/VI gaps Aurora
 * has no definition for anywhere -- still gets a shim here, identical to
 * shims_generated.c's own (still logging).
 */
#include "mp6_shim_log.h"
#include "dolphin.h"
#include "dolphin/thp.h"
#include "dolphin/mic.h"
#include "dolphin/m2s.h"
#include "dolphin/demo/DEMOStats.h"
#include "msm.h"

__attribute__((weak)) void DCFlushRange(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCFlushRange");
}

__attribute__((weak)) void DCFlushRangeNoSync(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCFlushRangeNoSync");
}

__attribute__((weak)) void DCInvalidateRange(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCInvalidateRange");
}

__attribute__((weak)) void DCStoreRange(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCStoreRange");
}

__attribute__((weak)) void DCStoreRangeNoSync(void* addr, u32 nBytes)
{
    MP6_LOG_ONCE("CACHE", "DCStoreRangeNoSync");
}

__attribute__((weak)) void DEMOPrintStats(void)
{
    MP6_LOG_ONCE("DEMO", "DEMOPrintStats");
}

__attribute__((weak)) void DEMOUpdateStats(unsigned char inc)
{
    MP6_LOG_ONCE("DEMO", "DEMOUpdateStats");
}

__attribute__((weak)) void DVDInit(void)
{
    MP6_LOG_ONCE("DVD", "DVDInit");
}

__attribute__((weak)) void GXAbortFrame(void)
{
    MP6_LOG_ONCE("GX", "GXAbortFrame");
}

__attribute__((weak)) void GXClearGPMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearGPMetric");
}

__attribute__((weak)) void GXClearMemMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearMemMetric");
}

__attribute__((weak)) void GXClearPixMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearPixMetric");
}

__attribute__((weak)) void GXClearVCacheMetric(void)
{
    MP6_LOG_ONCE("GX", "GXClearVCacheMetric");
}

__attribute__((weak)) f32 GXGetYScaleFactor(u16 efbHeight, u16 xfbHeight)
{
    MP6_LOG_ONCE("GX", "GXGetYScaleFactor");
    return (f32)0;
}

__attribute__((weak)) void GXReadGPMetric(u32* count0, u32* count1)
{
    MP6_LOG_ONCE("GX", "GXReadGPMetric");
}

__attribute__((weak)) void GXReadMemMetric(u32* cpReq, u32* tcReq, u32* cpuReadReq, u32* cpuWriteReq, u32* dspReq, u32* ioReq, u32* viReq, u32* peReq,
                            u32* rfReq, u32* fiReq)
{
    MP6_LOG_ONCE("GX", "GXReadMemMetric");
}

__attribute__((weak)) void GXReadPixMetric(u32* topIn, u32* topOut, u32* bottomIn, u32* bottomOut, u32* clearIn, u32* copyClocks)
{
    MP6_LOG_ONCE("GX", "GXReadPixMetric");
}

__attribute__((weak)) void GXReadVCacheMetric(u32* check, u32* miss, u32* stall)
{
    MP6_LOG_ONCE("GX", "GXReadVCacheMetric");
}

__attribute__((weak)) void GXResetWriteGatherPipe(void)
{
    MP6_LOG_ONCE("GX", "GXResetWriteGatherPipe");
}

__attribute__((weak)) void GXSetDrawSync(u16 token)
{
    MP6_LOG_ONCE("GX", "GXSetDrawSync");
}

__attribute__((weak)) GXDrawSyncCallback GXSetDrawSyncCallback(GXDrawSyncCallback callback)
{
    MP6_LOG_ONCE("GX", "GXSetDrawSyncCallback");
    return (GXDrawSyncCallback)0;
}

__attribute__((weak)) void GXWaitDrawDone(void)
{
    MP6_LOG_ONCE("GX", "GXWaitDrawDone");
}

__attribute__((weak)) void LCDisable(void)
{
    MP6_LOG_ONCE("LC", "LCDisable");
}

__attribute__((weak)) void LCEnable(void)
{
    MP6_LOG_ONCE("LC", "LCEnable");
}

__attribute__((weak)) void M2SAdvanceBuffer(s32 samples)
{
    MP6_LOG_ONCE("M2S", "M2SAdvanceBuffer");
}

__attribute__((weak)) void M2SClose(void)
{
    MP6_LOG_ONCE("M2S", "M2SClose");
}

__attribute__((weak)) s32 M2SGetSamples(s16** buffer, s32 samples)
{
    MP6_LOG_ONCE("M2S", "M2SGetSamples");
    return (s32)0;
}

__attribute__((weak)) s32 M2SGetSamplesLeft(void)
{
    MP6_LOG_ONCE("M2S", "M2SGetSamplesLeft");
    return (s32)0;
}

__attribute__((weak)) void M2SInit(void)
{
    MP6_LOG_ONCE("M2S", "M2SInit");
}

__attribute__((weak)) void M2SOpen(void)
{
    MP6_LOG_ONCE("M2S", "M2SOpen");
}

__attribute__((weak)) BOOL M2SSetActiveChannel(s32 chan)
{
    MP6_LOG_ONCE("M2S", "M2SSetActiveChannel");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetBuffer(s16* buffer)
{
    MP6_LOG_ONCE("M2S", "M2SSetBuffer");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetMode(s32 mode)
{
    MP6_LOG_ONCE("M2S", "M2SSetMode");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetPrerecordSamples(s32 milliseconds)
{
    MP6_LOG_ONCE("M2S", "M2SSetPrerecordSamples");
    return (BOOL)1;
}

__attribute__((weak)) BOOL M2SSetShifts(s32 shifts)
{
    MP6_LOG_ONCE("M2S", "M2SSetShifts");
    return (BOOL)1;
}

__attribute__((weak)) void M2SStart(void)
{
    MP6_LOG_ONCE("M2S", "M2SStart");
}

__attribute__((weak)) void M2SStop(void)
{
    MP6_LOG_ONCE("M2S", "M2SStop");
}

__attribute__((weak)) s32 MICGetButton(s32 chan, u32* button)
{
    MP6_LOG_ONCE("MIC", "MICGetButton");
    return (s32)0;
}

__attribute__((weak)) s32 MICGetDeviceID(s32 chan, u32* id)
{
    MP6_LOG_ONCE("MIC", "MICGetDeviceID");
    return (s32)0;
}

__attribute__((weak)) s32 MICGetSamples(s32 chan, s16* buffer, s32 index, s32 samples)
{
    MP6_LOG_ONCE("MIC", "MICGetSamples");
    return (s32)0;
}

__attribute__((weak)) s32 MICGetSamplesLeft(s32 chan, s32 index)
{
    MP6_LOG_ONCE("MIC", "MICGetSamplesLeft");
    return (s32)0;
}

__attribute__((weak)) void MICInit(void)
{
    MP6_LOG_ONCE("MIC", "MICInit");
}

__attribute__((weak)) BOOL MICIsActive(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICIsActive");
    return (BOOL)1;
}

__attribute__((weak)) s32 MICSetGain(s32 chan, s32 gain)
{
    MP6_LOG_ONCE("MIC", "MICSetGain");
    return (s32)0;
}

__attribute__((weak)) s32 MICStart(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICStart");
    return (s32)0;
}

__attribute__((weak)) s32 MICStop(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICStop");
    return (s32)0;
}

__attribute__((weak)) s32 MICUnmount(s32 chan)
{
    MP6_LOG_ONCE("MIC", "MICUnmount");
    return (s32)0;
}

__attribute__((weak)) s32 MICUpdateIndex(s32 chan, s32 index, s32 samples)
{
    MP6_LOG_ONCE("MIC", "MICUpdateIndex");
    return (s32)0;
}

__attribute__((weak)) void OSCancelThread(OSThread* thread)
{
    MP6_LOG_ONCE("OS", "OSCancelThread");
}

__attribute__((weak)) OSTime OSCheckStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSCheckStopwatch");
    return (OSTime)0;
}

__attribute__((weak)) void OSCreateAlarm(OSAlarm* alarm)
{
    MP6_LOG_ONCE("OS", "OSCreateAlarm");
}

__attribute__((weak)) BOOL OSCreateThread(OSThread* thread, void* (*func)(void*), void* param, void* stack, u32 stackSize,
                    OSPriority priority, u16 attr)
{
    MP6_LOG_ONCE("OS", "OSCreateThread");
    return (BOOL)1;
}

__attribute__((weak)) BOOL OSDisableInterrupts(void)
{
    MP6_LOG_ONCE("OS", "OSDisableInterrupts");
    return (BOOL)1;
}

__attribute__((weak)) BOOL OSEnableInterrupts(void)
{
    MP6_LOG_ONCE("OS", "OSEnableInterrupts");
    return (BOOL)1;
}

__attribute__((weak)) u32 OSGetConsoleSimulatedMemSize(void)
{
    MP6_LOG_ONCE("OS", "OSGetConsoleSimulatedMemSize");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetConsoleType(void)
{
    MP6_LOG_ONCE("OS", "OSGetConsoleType");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetPhysicalMemSize(void)
{
    MP6_LOG_ONCE("OS", "OSGetPhysicalMemSize");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetProgressiveMode(void)
{
    MP6_LOG_ONCE("OS", "OSGetProgressiveMode");
    return (u32)0;
}

__attribute__((weak)) BOOL OSGetResetButtonState(void)
{
    MP6_LOG_ONCE("OS", "OSGetResetButtonState");
    return (BOOL)1;
}

__attribute__((weak)) u32 OSGetResetCode(void)
{
    MP6_LOG_ONCE("OS", "OSGetResetCode");
    return (u32)0;
}

__attribute__((weak)) u32 OSGetSoundMode(void)
{
    MP6_LOG_ONCE("OS", "OSGetSoundMode");
    return (u32)0;
}

__attribute__((weak)) void OSInit(void)
{
    MP6_LOG_ONCE("OS", "OSInit");
}

__attribute__((weak)) void OSInitMessageQueue(OSMessageQueue* mq, OSMessage* msgArray, s32 msgCount)
{
    MP6_LOG_ONCE("OS", "OSInitMessageQueue");
}

__attribute__((weak)) void OSInitStopwatch(OSStopwatch* sw, char* name)
{
    MP6_LOG_ONCE("OS", "OSInitStopwatch");
}

__attribute__((weak)) void OSInitThreadQueue(OSThreadQueue* queue)
{
    MP6_LOG_ONCE("OS", "OSInitThreadQueue");
}

__attribute__((weak)) BOOL OSReceiveMessage(OSMessageQueue* mq, OSMessage* msg, s32 flags)
{
    MP6_LOG_ONCE("OS", "OSReceiveMessage");
    return (BOOL)1;
}

__attribute__((weak)) void OSResetStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSResetStopwatch");
}

__attribute__((weak)) void OSResetSystem(s32 reset, u32 resetCode, BOOL forceMenu)
{
    MP6_LOG_ONCE("OS", "OSResetSystem");
}

__attribute__((weak)) BOOL OSRestoreInterrupts(BOOL level)
{
    MP6_LOG_ONCE("OS", "OSRestoreInterrupts");
    return (BOOL)1;
}

__attribute__((weak)) s32 OSResumeThread(OSThread* thread)
{
    MP6_LOG_ONCE("OS", "OSResumeThread");
    return (s32)0;
}

__attribute__((weak)) BOOL OSSendMessage(OSMessageQueue* mq, OSMessage msg, s32 flags)
{
    MP6_LOG_ONCE("OS", "OSSendMessage");
    return (BOOL)1;
}

__attribute__((weak)) void OSSetAlarm(OSAlarm* alarm, OSTime tick, OSAlarmHandler handler)
{
    MP6_LOG_ONCE("OS", "OSSetAlarm");
}

__attribute__((weak)) OSErrorHandler OSSetErrorHandler(OSError code, OSErrorHandler handler)
{
    MP6_LOG_ONCE("OS", "OSSetErrorHandler");
    return (OSErrorHandler)0;
}

__attribute__((weak)) OSThread* OSSetIdleFunction(OSIdleFunction idleFunction, void* param, void* stack, u32 stackSize)
{
    MP6_LOG_ONCE("OS", "OSSetIdleFunction");
    return (OSThread*)0;
}

__attribute__((weak)) void OSSetProgressiveMode(u32 on)
{
    MP6_LOG_ONCE("OS", "OSSetProgressiveMode");
}

__attribute__((weak)) BOOL OSSetThreadPriority(OSThread* thread, OSPriority priority)
{
    MP6_LOG_ONCE("OS", "OSSetThreadPriority");
    return (BOOL)1;
}

__attribute__((weak)) void OSSleepThread(OSThreadQueue* queue)
{
    MP6_LOG_ONCE("OS", "OSSleepThread");
}

__attribute__((weak)) void OSStartStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSStartStopwatch");
}

__attribute__((weak)) void OSStopStopwatch(OSStopwatch* sw)
{
    MP6_LOG_ONCE("OS", "OSStopStopwatch");
}

__attribute__((weak)) s32 OSSuspendThread(OSThread* thread)
{
    MP6_LOG_ONCE("OS", "OSSuspendThread");
    return (s32)0;
}

__attribute__((weak)) void OSWakeupThread(OSThreadQueue* queue)
{
    MP6_LOG_ONCE("OS", "OSWakeupThread");
}

__attribute__((weak)) void OSYieldThread(void)
{
    MP6_LOG_ONCE("OS", "OSYieldThread");
}

__attribute__((weak)) void PPCSync(void)
{
    MP6_LOG_ONCE("CACHE", "PPCSync");
}

__attribute__((weak)) u32 SIProbe(s32 chan)
{
    MP6_LOG_ONCE("SI", "SIProbe");
    return (u32)0;
}

__attribute__((weak)) void SISetSamplingRate(u32 msec)
{
    MP6_LOG_ONCE("SI", "SISetSamplingRate");
}

__attribute__((weak)) u32 THPAudioDecode(s16* audioBuffer, u8* audioFrame, s32 flag)
{
    MP6_LOG_ONCE("THP", "THPAudioDecode");
    return (u32)0;
}

__attribute__((weak)) s32 THPVideoDecode(void* file, void* tileY, void* tileU, void* tileV, void* work)
{
    MP6_LOG_ONCE("THP", "THPVideoDecode");
    return (s32)0;
}

__attribute__((weak)) u32 VIGetDTVStatus(void)
{
    MP6_LOG_ONCE("VI", "VIGetDTVStatus");
    return (u32)0;
}

__attribute__((weak)) void VISetBlack(BOOL black)
{
    MP6_LOG_ONCE("VI", "VISetBlack");
}

__attribute__((weak)) void VISetNextFrameBuffer(void* fb)
{
    MP6_LOG_ONCE("VI", "VISetNextFrameBuffer");
}

__attribute__((weak)) VIRetraceCallback VISetPostRetraceCallback(VIRetraceCallback callback)
{
    MP6_LOG_ONCE("VI", "VISetPostRetraceCallback");
    return (VIRetraceCallback)0;
}

__attribute__((weak)) VIRetraceCallback VISetPreRetraceCallback(VIRetraceCallback callback)
{
    MP6_LOG_ONCE("VI", "VISetPreRetraceCallback");
    return (VIRetraceCallback)0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_Close; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_Close()
{
    MP6_LOG_ONCE("OS", "gsapi_Close");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextActivate; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextActivate()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextActivate");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextDeActivate; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextDeActivate()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextDeActivate");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetCtxData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetCtxData()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetCtxData");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetGcdData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetGcdData()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetGcdData");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetParam; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetParam()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetParam");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_ContextSetWrdData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_ContextSetWrdData()
{
    MP6_LOG_ONCE("OS", "gsapi_ContextSetWrdData");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineClose; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineClose()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineClose");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineOpen; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineOpen()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineOpen");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineRestart; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineRestart()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineRestart");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSessionDataExport; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSessionDataExport()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSessionDataExport");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSessionDataFree; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSessionDataFree()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSessionDataFree");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSessionDataImport; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSessionDataImport()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSessionDataImport");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSetMode; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSetMode()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSetMode");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineSetParam; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineSetParam()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineSetParam");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineStart; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineStart()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineStart");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_EngineStop; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_EngineStop()
{
    MP6_LOG_ONCE("OS", "gsapi_EngineStop");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_Init; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_Init()
{
    MP6_LOG_ONCE("OS", "gsapi_Init");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_LanguageLoadBuffer; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_LanguageLoadBuffer()
{
    MP6_LOG_ONCE("OS", "gsapi_LanguageLoadBuffer");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_LanguageUnLoad; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_LanguageUnLoad()
{
    MP6_LOG_ONCE("OS", "gsapi_LanguageUnLoad");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_NotifySetCallback; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_NotifySetCallback()
{
    MP6_LOG_ONCE("OS", "gsapi_NotifySetCallback");
    return 0;
}

/* TODO: no prototype found in include/dolphin or include/msm for gsapi_SetUserData; K&R empty-parens fallback accepts any args. Weak (see make_stub's comment). */
__attribute__((weak)) int gsapi_SetUserData()
{
    MP6_LOG_ONCE("OS", "gsapi_SetUserData");
    return 0;
}

__attribute__((weak)) void msmMusFdoutEnd(void)
{
    MP6_LOG_ONCE("MSM", "msmMusFdoutEnd");
}

__attribute__((weak)) s32 msmMusGetMidiCtrl(int musNo, s32 channel, s32 ctrl)
{
    MP6_LOG_ONCE("MSM", "msmMusGetMidiCtrl");
    return (s32)0;
}

__attribute__((weak)) s32 msmMusGetNumPlay(BOOL baseGrp)
{
    MP6_LOG_ONCE("MSM", "msmMusGetNumPlay");
    return (s32)0;
}

__attribute__((weak)) s32 msmMusGetStatus(int musNo)
{
    MP6_LOG_ONCE("MSM", "msmMusGetStatus");
    return (s32)0;
}

__attribute__((weak)) s32 msmMusPauseAll(BOOL pause, s32 speed)
{
    MP6_LOG_ONCE("MSM", "msmMusPauseAll");
    return (s32)0;
}

__attribute__((weak)) int msmMusPlay(int musId, MSM_MUSPARAM *musParam)
{
    MP6_LOG_ONCE("MSM", "msmMusPlay");
    return (int)0;
}

__attribute__((weak)) void msmMusSetMasterVolume(int volume)
{
    MP6_LOG_ONCE("MSM", "msmMusSetMasterVolume");
}

__attribute__((weak)) s32 msmMusStop(int musNo, s32 speed)
{
    MP6_LOG_ONCE("MSM", "msmMusStop");
    return (s32)0;
}

__attribute__((weak)) void msmMusStopAll(BOOL checkGrp, s32 speed)
{
    MP6_LOG_ONCE("MSM", "msmMusStopAll");
}

__attribute__((weak)) void msmSeDelListener(void)
{
    MP6_LOG_ONCE("MSM", "msmSeDelListener");
}

__attribute__((weak)) s32 msmSeGetEntryID(s16 seId, int *seNo)
{
    MP6_LOG_ONCE("MSM", "msmSeGetEntryID");
    return (s32)0;
}

__attribute__((weak)) MSMSE * msmSeGetIndexPtr(s32 seId)
{
    MP6_LOG_ONCE("MSM", "msmSeGetIndexPtr");
    return (MSMSE *)0;
}

__attribute__((weak)) s32 msmSeGetNumPlay(BOOL baseGrp)
{
    MP6_LOG_ONCE("MSM", "msmSeGetNumPlay");
    return (s32)0;
}

__attribute__((weak)) s32 msmSeSetListener(Vec *pos, Vec *heading, float sndDist, float sndSpeed, MSM_SELISTENER *listener)
{
    MP6_LOG_ONCE("MSM", "msmSeSetListener");
    return (s32)0;
}

__attribute__((weak)) s32 msmSeUpdataListener(Vec *pos, Vec *heading)
{
    MP6_LOG_ONCE("MSM", "msmSeUpdataListener");
    return (s32)0;
}

__attribute__((weak)) void msmSysCheckInit(void)
{
    MP6_LOG_ONCE("MSM", "msmSysCheckInit");
}

__attribute__((weak)) s32 msmSysSetAux(s32 auxA, s32 auxB)
{
    MP6_LOG_ONCE("MSM", "msmSysSetAux");
    return (s32)0;
}

__attribute__((weak)) void msmSysSetOutputMode(SND_OUTPUTMODE mode)
{
    MP6_LOG_ONCE("MSM", "msmSysSetOutputMode");
}
