/* MP6 native port -- cross-session savestate capture/restore.
 * See shim/include/mp6_savestate.h for the design rationale and the
 * carve-out contract.
 *
 * FILE LAYOUT
 *   [Mp6SavestateHeader]            fixed-size, uncompressed, validated first
 *   [Mp6SavestateRegion  x nRegion] fixed-size table, uncompressed
 *   [deflate stream]                every region's bytes, concatenated in
 *                                   table order, compressed as ONE stream
 *
 * The payload is one continuous deflate stream rather than per-region
 * blobs because the arena is 256 MB of which the overwhelming majority is
 * untouched zeros -- a single stream lets those collapse across region
 * boundaries too, and keeps the writer a simple "feed everything through
 * once" loop instead of per-region bookkeeping.
 *
 * FAIL-CLOSED DISCIPLINE. mp6_savestate_restore() validates the header,
 * every base address, and the build fingerprint, and fully decompresses
 * into scratch memory BEFORE writing a single byte of live game memory.
 * A corrupt, truncated, foreign-build, or differently-based state file can
 * therefore only ever produce a clean error return -- never a half-restored
 * process. This mirrors the existing mp6_assert_image_low convention: prove
 * the invariant or refuse, never proceed on a maybe.
 */
#include "mp6_savestate.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "host.h"
#include "zlib.h"
#include "mp6_boot.h" /* mp6_max_ticks/mp6_ticks_unlimited -- latched across restore */

/* SAVESTATE CARVE-OUT. Placing this AFTER this TU's own
 * includes is load-bearing, not stylistic: it is a #pragma clang section that
 * redirects every file-scope definition FOLLOWING it. As a -include (before all
 * headers) it also captured the decomp headers' C TENTATIVE definitions --
 * dolphin/os.h:27 `u32 __OSBusClock;` and friends -- turning those common
 * symbols into strong per-TU definitions and breaking the link with duplicate
 * symbol errors. Here, headers keep their normal linkage and only this file's
 * own statics move. tools/build.py asserts this line exists in every TU listed
 * in HOST_STATE_SECTION_SOURCES. */
#include "mp6_host_section.h"


/* Arena accessors (platform/os/arena.c). Declared here rather than in a
 * header because arena.c exposes no header of its own; these two have
 * existed as an ABI with no consumer until now. */
extern void *mp6_arena_base(void);
extern unsigned int mp6_arena_size(void);

/* The build fingerprint: a sha1 over EVERY link input (all objects, plus the
 * aurora archives/import libs on the windowed row), computed by build.py at
 * link time and injected via a tiny autogenerated TU. A savestate is only
 * meaningful against the exact binary that produced it -- a rebuild moves
 * code and data even at a fixed image base, so a captured coroutine stack's
 * return addresses would point into the wrong functions.
 *
 * This REPLACES an earlier __DATE__/__TIME__-of-this-TU stamp, which a code
 * review confirmed was a broken guard: build.py's needs_rebuild() only
 * recompiles savestate.o when savestate.c itself (or build.py, or a shared
 * header tree) changes, so editing any OTHER .c relinked a new exe still
 * carrying the old timestamp -- and the same-binary check silently accepted
 * a stale state against moved code. A link-input hash cannot go stale that
 * way, and has the bonus that a no-op rebuild keeps existing states valid
 * (identical inputs, identical hash) where a timestamp would have
 * invalidated them for nothing. */
extern const char mp6_link_stamp[]; /* build/mp6_link_stamp_<mode>.c, autogenerated */

/* Address anchor for the image-base proxy below -- any static in this TU
 * works; it only has to live at a fixed link-time address. */
static const char kImageAnchor[] = "mp6-savestate-anchor";

/* Set once a restore succeeds. Lives in this file's carved-out statics, so
 * it describes the RUNNING process (a restored state can never smuggle in
 * a stale value of it). */
static int g_wasRestored;

int mp6_savestate_was_restored(void) { return g_wasRestored; }

void mp6_savestate_guarded_exit(int code)
{
    fflush(stdout);
    fflush(stderr);
    if (g_wasRestored) {
        /* Third-party teardown over restored state is the one crash class the
         * denylist carve-out cannot fully close (static CRT globals are
         * un-annotatable) -- so a restored process does not run it at all.
         * See mp6_savestate.h's guarded-exit comment. */
        _exit(code);
    }
    exit(code);
}

#define MP6_SAVESTATE_MAX_REGIONS 160

/* Region kinds, recorded so a restore can apply per-kind policy and so a
 * human reading a hexdump can tell what they are looking at. */
enum {
    MP6_SS_REGION_ARENA = 1,
    MP6_SS_REGION_IMAGE = 2, /* one writable PE section (never the carve-out) */
    MP6_SS_REGION_CORO  = 3, /* one in-use coroutine pool slot */
    MP6_SS_REGION_ARAM  = 4  /* the fake-ARAM backing buffer -- host heap, UNPINNED address */
};

/* The fake-ARAM buffer (platform/null/shims_manual.c). Declared here rather
 * than in a header because shims_manual.c publishes no header of its own. */
extern void *mp6_aram_savestate_buffer(size_t *sizeOut);

typedef struct {
    uint32_t kind;
    uint32_t index;   /* coro slot index for CORO; else 0 */
    uint64_t addr;    /* absolute address at capture time -- must match on load */
    uint64_t size;
    char     name[16];
} Mp6SavestateRegion;

typedef struct {
    uint32_t magic;
    uint32_t version;
    char     buildStamp[48]; /* sha1 hex (40) + NUL, from mp6_link_stamp */
    uint64_t arenaBase;
    uint64_t arenaSize;
    uint64_t coroPoolBase;
    uint64_t coroPoolSize;
    uint64_t imageBase;
    uint32_t regionCount;
    uint32_t reserved;
    uint64_t rawBytes;        /* sum of region sizes, for the decompress buffer */
    uint64_t compressedBytes; /* deflate stream length that follows the table --
                               * ALSO the offset key for the widescreen blob
                               * below (blob = header + table + this many bytes) */
    uint64_t wsNativeBytes;   /* widescreen native-snapshot blob, stored
                               * UNCOMPRESSED after the deflate stream (small --
                               * KBs of vertex floats) */
    /* the mixer's own view at capture time. Carried in the header rather
     * than as a region because it is small, fixed-size, and -- unlike every
     * region -- has no address to be restored TO; it is replayed through the
     * msm API instead. See mp6_savestate.h for why it must be captured at
     * all (the playing BGM stream id exists nowhere else in the process). */
    Mp6SsAudioShadow audio;
} Mp6SavestateHeader;

/* ------------------------------------------------------------------ */

const char *mp6_savestate_strerror(int result)
{
    switch (result) {
    case MP6_SAVESTATE_OK:                    return "ok";
    case MP6_SAVESTATE_ERR_IO:                return "file I/O failed";
    case MP6_SAVESTATE_ERR_FORMAT:            return "not a savestate, or truncated/wrong version";
    case MP6_SAVESTATE_ERR_BINARY_MISMATCH:   return "captured by a DIFFERENT build of the exe -- rebuild invalidates savestates";
    case MP6_SAVESTATE_ERR_LAYOUT_MISMATCH:   return "memory landed at a different address this run -- state cannot be applied";
    case MP6_SAVESTATE_ERR_UNSUPPORTED:       return "no capturable coroutine pool (fiber backend)";
    case MP6_SAVESTATE_ERR_NOMEM:             return "out of memory";
    default:                                  return "unknown error";
    }
}

/* Image base, as the savestate means it: the load address of the running
 * module. Derived from a known-static address rather than re-querying the
 * OS so this file needs no windows.h (host_win32.c is the only TU allowed
 * to include it). Any writable section's address is a fixed offset from the
 * image base, so section addresses are compared individually anyway -- this
 * value exists for the error message and for a fast early reject. */
static uint64_t mp6_ss_image_base_proxy(void)
{
    return (uint64_t)(uintptr_t)&kImageAnchor[0];
}

/* Collects the regions this build would capture. Shared by capture and
 * restore so the two can never disagree about what the set should be --
 * restore then checks the file's table against this. */
static int mp6_ss_collect_regions(Mp6SavestateRegion *out, int maxOut, uint64_t *rawBytesOut)
{
    Mp6HostImageSection sections[64];
    int nSect, i, n = 0;
    uint64_t raw = 0;

    if (mp6_arena_base() == NULL || mp6_coro_pool_base() == NULL) {
        return -1;
    }

    /* 1. The game arena, whole. Capturing all 256 MB rather than only the
     * live heap prefix is deliberate: the arena's bump allocation is
     * per-heap, not arena-global, so "the live set" is a union of ranges
     * whose upper bounds sit near the end of each heap almost immediately
     * after boot -- the naive prefix would save far less than it appears
     * to, while adding a way to under-capture. The untouched remainder is
     * zeros, which deflate collapses to nearly nothing. */
    if (n >= maxOut) return -1;
    out[n].kind = MP6_SS_REGION_ARENA;
    out[n].index = 0;
    out[n].addr = (uint64_t)(uintptr_t)mp6_arena_base();
    out[n].size = (uint64_t)mp6_arena_size();
    snprintf(out[n].name, sizeof(out[n].name), "arena");
    raw += out[n].size;
    n++;

    /* 2. Every writable image section EXCEPT the host-owned carve-out. */
    nSect = mp6_host_image_writable_sections(sections, (int)(sizeof(sections) / sizeof(sections[0])));
    if (nSect <= 0) {
        return -1;
    }
    for (i = 0; i < nSect; i++) {
        if (strcmp(sections[i].name, MP6_HOST_STATE_SECTION_BSS) == 0 ||
            strcmp(sections[i].name, MP6_HOST_STATE_SECTION_DATA) == 0) {
            continue; /* host-thread-owned / OS handles -- see mp6_savestate.h */
        }
        if (strcmp(sections[i].name, ".tls") == 0) {
            /* Thread-local storage TEMPLATE data, not the live per-thread
             * copies. It belongs to the host threading model (and the
             * #pragma clang section carve-out provably cannot reach TLS
             * variables), so restoring it can only ever install another
             * process's thread-local seed values over this one's. */
            continue;
        }
        if (n >= maxOut) return -1;
        out[n].kind = MP6_SS_REGION_IMAGE;
        out[n].index = 0;
        out[n].addr = (uint64_t)(uintptr_t)sections[i].addr;
        out[n].size = (uint64_t)sections[i].size;
        snprintf(out[n].name, sizeof(out[n].name), "%s", sections[i].name);
        raw += out[n].size;
        n++;
    }

    /* 2b. The fake-ARAM backing buffer. It is 16 MB of host calloc, so
     * neither the arena sweep nor the image sweep covers it -- and its
     * CONTENTS are the load-bearing part, not just its pointer. game/armem.c's
     * residency table (ARInfo/ARBase) is ordinary decomp .bss and IS
     * restored, while the bytes it indexes are not; HuAR_DVDtoARAM early-outs
     * on HuARDirCheck, so a rewound table claims "already cached" and the DMA
     * that would refill ARAM never runs again. Capturing only the pointer
     * (or merely re-pointing it) would therefore trade a crash for SILENT
     * asset corruption on the same path. The address recorded here is
     * advisory -- restore copies into whatever buffer the live process
     * allocated (see the commit loop). */
    {
        size_t aramSize = 0;
        void *aram = mp6_aram_savestate_buffer(&aramSize);
        if (aram != NULL && aramSize > 0) {
            if (n >= maxOut) return -1;
            out[n].kind = MP6_SS_REGION_ARAM;
            out[n].index = 0;
            out[n].addr = (uint64_t)(uintptr_t)aram;
            out[n].size = (uint64_t)aramSize;
            snprintf(out[n].name, sizeof(out[n].name), "aram");
            raw += out[n].size;
            n++;
        }
    }

    /* 3. Each in-use coroutine slot, whole (header + stack). */
    for (i = 0; i < mp6_coro_slot_count(); i++) {
        if (!mp6_coro_slot_in_use(i)) {
            continue;
        }
        if (n >= maxOut) return -1;
        out[n].kind = MP6_SS_REGION_CORO;
        out[n].index = (uint32_t)i;
        out[n].addr = (uint64_t)(uintptr_t)mp6_coro_slot_addr(i);
        out[n].size = (uint64_t)mp6_coro_slot_size();
        snprintf(out[n].name, sizeof(out[n].name), "coro%d", i);
        raw += out[n].size;
        n++;
    }

    if (rawBytesOut) {
        *rawBytesOut = raw;
    }
    return n;
}

/* ------------------------------------------------------------------ */

int mp6_savestate_capture(const char *path)
{
    Mp6SavestateRegion regions[MP6_SAVESTATE_MAX_REGIONS];
    Mp6SavestateHeader hdr;
    uint64_t rawBytes = 0;
    int nRegion, i, rc = MP6_SAVESTATE_OK;
    FILE *f = NULL;
    z_stream zs;
    unsigned char *outBuf = NULL;
    const size_t kChunk = 1u << 20;
    int zInit = 0;
    char tmpPath[560];

    if (path == NULL) {
        return MP6_SAVESTATE_ERR_IO;
    }
    if (mp6_coro_pool_base() == NULL) {
        return MP6_SAVESTATE_ERR_UNSUPPORTED;
    }
    /* zero the table before filling. collect fills name[16]
     * via snprintf, which writes only the chars + NUL -- without this memset
     * the tails are uninitialized stack bytes, fwritten into a file users
     * hand to other people (nondeterministic artifacts + a small info leak). */
    memset(regions, 0, sizeof(regions));
    nRegion = mp6_ss_collect_regions(regions, MP6_SAVESTATE_MAX_REGIONS, &rawBytes);
    if (nRegion <= 0) {
        /* collect failing means the platform cannot enumerate
         * its regions (Android's writable-section walk returns 0 by design)
         * -- that is "unsupported here", not "corrupt file". ERR_FORMAT's
         * message ("not a savestate, or truncated") sent users chasing file
         * corruption for a file that was never opened. */
        return MP6_SAVESTATE_ERR_UNSUPPORTED;
    }

    /* A load-bearing assumption, checked instead of trusted: the DVD
     * layer's open-handle table must be empty at any capture point, because
     * that table is carved out and records no path/entrynum, so an open file
     * cannot be re-established on restore. It is empty in this build (no
     * compiled caller holds a DVD file across a frame boundary -- see
     * platform/dvd/dvd_files.c's own comment). Enabling THP or compiling
     * msmstream.c would break that, and this is how you would find out:
     * loudly, at capture, rather than as a mystery corruption on load. */
    if (mp6_dvd_open_handle_count() != 0) {
        fprintf(stderr,
                "[SAVESTATE] WARNING: %d DVD file handle(s) open at capture. Restored state "
                "will refer to files this savestate cannot reopen (the table needs splitting "
                "into {key,entrynum} + a carved-out {FILE*}).\n",
                mp6_dvd_open_handle_count());
        fflush(stderr);
    }

    memset(&hdr, 0, sizeof(hdr));
    hdr.magic = MP6_SAVESTATE_MAGIC;
    hdr.version = MP6_SAVESTATE_VERSION;
    snprintf(hdr.buildStamp, sizeof(hdr.buildStamp), "%s", mp6_link_stamp);
    hdr.arenaBase = (uint64_t)(uintptr_t)mp6_arena_base();
    hdr.arenaSize = (uint64_t)mp6_arena_size();
    hdr.coroPoolBase = (uint64_t)(uintptr_t)mp6_coro_pool_base();
    hdr.coroPoolSize = (uint64_t)mp6_coro_pool_size();
    hdr.imageBase = mp6_ss_image_base_proxy();
    hdr.regionCount = (uint32_t)nRegion;
    hdr.rawBytes = rawBytes;
    hdr.compressedBytes = 0; /* patched below once known */
    mp6_msm_savestate_capture(&hdr.audio);

    /* S2 (review): write to a TEMP file and rename over the slot only after
     * the whole capture is proven on disk. fopen(path,"wb") truncated the
     * user's existing good state in place, so a failed capture -- disk full,
     * AV lock, a crash mid-deflate -- destroyed the very repro they meant to
     * keep. save and load share one slot path, which makes that loss total. */
    snprintf(tmpPath, sizeof(tmpPath), "%s.tmp", path);
    f = fopen(tmpPath, "wb");
    if (f == NULL) {
        return MP6_SAVESTATE_ERR_IO;
    }
    if (fwrite(&hdr, sizeof(hdr), 1, f) != 1 ||
        fwrite(regions, sizeof(regions[0]), (size_t)nRegion, f) != (size_t)nRegion) {
        rc = MP6_SAVESTATE_ERR_IO;
        goto done;
    }

    outBuf = (unsigned char *)malloc(kChunk);
    if (outBuf == NULL) {
        rc = MP6_SAVESTATE_ERR_NOMEM;
        goto done;
    }
    memset(&zs, 0, sizeof(zs));
    /* Level 1: this is a debugging tool run interactively, and the bulk of
     * the payload is long zero runs that even the fastest level collapses
     * completely. Spending seconds of the user's time on level 9 to shave
     * a mostly-zero stream is the wrong trade. */
    if (deflateInit(&zs, 1) != Z_OK) {
        rc = MP6_SAVESTATE_ERR_NOMEM;
        goto done;
    }
    zInit = 1;

    for (i = 0; i < nRegion; i++) {
        zs.next_in = (Bytef *)(uintptr_t)regions[i].addr;
        zs.avail_in = (uInt)regions[i].size;
        /* Region sizes here are well under 4 GB each, so one avail_in pass
         * per region is safe; the loop below drains as many output chunks
         * as that input produces. */
        while (zs.avail_in > 0) {
            zs.next_out = outBuf;
            zs.avail_out = (uInt)kChunk;
            if (deflate(&zs, Z_NO_FLUSH) != Z_OK) {
                rc = MP6_SAVESTATE_ERR_IO;
                goto done;
            }
            {
                size_t produced = kChunk - zs.avail_out;
                if (produced && fwrite(outBuf, 1, produced, f) != produced) {
                    rc = MP6_SAVESTATE_ERR_IO;
                    goto done;
                }
            }
        }
    }
    /* Flush the deflate tail. */
    for (;;) {
        int zr;
        size_t produced;
        zs.next_out = outBuf;
        zs.avail_out = (uInt)kChunk;
        zr = deflate(&zs, Z_FINISH);
        produced = kChunk - zs.avail_out;
        if (produced && fwrite(outBuf, 1, produced, f) != produced) {
            rc = MP6_SAVESTATE_ERR_IO;
            goto done;
        }
        if (zr == Z_STREAM_END) {
            break;
        }
        if (zr != Z_OK) {
            rc = MP6_SAVESTATE_ERR_IO;
            goto done;
        }
    }

    hdr.compressedBytes = (uint64_t)zs.total_out;

    /* append the widescreen native-snapshot blob (see
     * mp6_widescreen_savestate_blob_size's comment for why these host-heap
     * buffers are game state that must travel in the file). Uncompressed --
     * it is KBs against a multi-MB file. */
    {
        size_t wsSize = mp6_widescreen_savestate_blob_size();
        void *wsBuf = malloc(wsSize > 0 ? wsSize : 1);
        if (wsBuf == NULL) {
            rc = MP6_SAVESTATE_ERR_NOMEM;
            goto done;
        }
        mp6_widescreen_savestate_blob_write(wsBuf);
        if (wsSize > 0 && fwrite(wsBuf, 1, wsSize, f) != wsSize) {
            free(wsBuf);
            rc = MP6_SAVESTATE_ERR_IO;
            goto done;
        }
        free(wsBuf);
        hdr.wsNativeBytes = (uint64_t)wsSize;
    }

    if (fseek(f, 0, SEEK_SET) != 0 || fwrite(&hdr, sizeof(hdr), 1, f) != 1) {
        rc = MP6_SAVESTATE_ERR_IO;
        goto done;
    }

    /* the final buffered chunk (and the rewritten header)
     * only reach the disk at flush/close -- check BOTH before claiming
     * success, or a disk-full/AV-lock truncation ships as a "captured"
     * file that fails on the recipient's machine with a corruption error. */
    if (fflush(f) != 0 || ferror(f) || fclose(f) != 0) {
        f = NULL; /* closed (or unusable) either way -- don't double-close */
        rc = MP6_SAVESTATE_ERR_IO;
        goto done;
    }
    f = NULL;
    /* Atomic-enough publish: drop any previous slot content, then rename the
     * fully-written temp into place. On any failure the old state may already
     * be gone (remove succeeded, rename failed -- a genuinely torn window),
     * but the temp file still holds the complete new capture, and the error
     * message names it so nothing is lost. */
    remove(path);
    if (rename(tmpPath, path) != 0) {
        fprintf(stderr, "[SAVESTATE] rename failed -- the capture is intact at %s\n", tmpPath);
        rc = MP6_SAVESTATE_ERR_IO;
        goto done;
    }

    printf("[SAVESTATE] captured %s: %d regions, %.1f MB raw -> %.1f MB compressed\n",
           path, nRegion,
           (double)rawBytes / (1024.0 * 1024.0),
           (double)zs.total_out / (1024.0 * 1024.0));
    fflush(stdout);

done:
    if (zInit) {
        deflateEnd(&zs);
    }
    free(outBuf);
    if (f) {
        fclose(f);
        remove(tmpPath); /* failed capture: clean up the partial temp, leave the old slot alone */
    }
    return rc;
}

/* ------------------------------------------------------------------ */

int mp6_savestate_restore(const char *path)
{
    Mp6SavestateRegion fileRegions[MP6_SAVESTATE_MAX_REGIONS];
    Mp6SavestateHeader hdr;
    FILE *f = NULL;
    unsigned char *raw = NULL;
    unsigned char *inBuf = NULL;
    z_stream zs;
    int zInit = 0, rc = MP6_SAVESTATE_OK, i;
    uint64_t off;
    const size_t kChunk = 1u << 20;

    if (path == NULL) {
        return MP6_SAVESTATE_ERR_IO;
    }
    f = fopen(path, "rb");
    if (f == NULL) {
        return MP6_SAVESTATE_ERR_IO;
    }
    if (fread(&hdr, sizeof(hdr), 1, f) != 1) {
        rc = MP6_SAVESTATE_ERR_FORMAT;
        goto done;
    }
    if (hdr.magic != MP6_SAVESTATE_MAGIC || hdr.version != MP6_SAVESTATE_VERSION ||
        hdr.regionCount == 0 || hdr.regionCount > MP6_SAVESTATE_MAX_REGIONS) {
        rc = MP6_SAVESTATE_ERR_FORMAT;
        goto done;
    }
    if (strncmp(hdr.buildStamp, mp6_link_stamp, sizeof(hdr.buildStamp)) != 0) {
        fprintf(stderr, "[SAVESTATE] refusing: state built %s, this exe built %s\n",
                hdr.buildStamp, mp6_link_stamp);
        rc = MP6_SAVESTATE_ERR_BINARY_MISMATCH;
        goto done;
    }
    /* Address pinning. These are MEASURED-stable, not guaranteed -- so they
     * are re-checked here every single load, and a mismatch is refused
     * loudly rather than "relocated" by guesswork. A 256 MB window is wide
     * enough that ordinary integers alias into it, so a blind
     * add-a-delta-to-anything-in-range pass would have a real
     * false-positive rate and could corrupt state silently. Refusing is the
     * honest outcome. */
    if (hdr.arenaBase != (uint64_t)(uintptr_t)mp6_arena_base() ||
        hdr.arenaSize != (uint64_t)mp6_arena_size() ||
        hdr.coroPoolBase != (uint64_t)(uintptr_t)mp6_coro_pool_base() ||
        hdr.imageBase != mp6_ss_image_base_proxy()) {
        fprintf(stderr,
                "[SAVESTATE] refusing: address layout differs from capture "
                "(arena %llx vs %llx, coro %llx vs %llx, image %llx vs %llx)\n",
                (unsigned long long)hdr.arenaBase, (unsigned long long)(uintptr_t)mp6_arena_base(),
                (unsigned long long)hdr.coroPoolBase, (unsigned long long)(uintptr_t)mp6_coro_pool_base(),
                (unsigned long long)hdr.imageBase, (unsigned long long)mp6_ss_image_base_proxy());
        rc = MP6_SAVESTATE_ERR_LAYOUT_MISMATCH;
        goto done;
    }
    if (fread(fileRegions, sizeof(fileRegions[0]), hdr.regionCount, f) != hdr.regionCount) {
        rc = MP6_SAVESTATE_ERR_FORMAT;
        goto done;
    }
    /* Validate the WHOLE region table against the live process. The
     * table is uncompressed and sits OUTSIDE the
     * adler-protected deflate stream, so a bit-flip or hand-truncation here
     * could survive every header check -- and each non-CORO entry is a
     * memcpy DESTINATION. The earlier revision checked only CORO addresses
     * and size!=0, which left the commit loop trusting file-supplied
     * addresses; that is a wild write, not fail-closed.
     *
     * Method: re-collect this process's own region set (the same function
     * capture used, so the two literally cannot drift) and require the
     * file's non-CORO entries to match it one-for-one, in order. CORO
     * entries are validated by FORMULA instead (slot address arithmetic),
     * because the captured in-use slot set legitimately differs from the
     * restoring process's own. ARAM's addr is advisory (host heap, per-
     * process) -- size must match, address is ignored. Finally the region
     * sizes must sum exactly to hdr.rawBytes, or the commit loop's running
     * offset would walk off the scratch buffer. */
    {
        Mp6SavestateRegion expect[MP6_SAVESTATE_MAX_REGIONS];
        uint64_t expectRaw = 0, sum = 0;
        int nExpect, e = 0, coroSeen = 0;

        memset(expect, 0, sizeof(expect));
        nExpect = mp6_ss_collect_regions(expect, MP6_SAVESTATE_MAX_REGIONS, &expectRaw);
        if (nExpect <= 0) {
            rc = MP6_SAVESTATE_ERR_UNSUPPORTED;
            goto done;
        }
        for (i = 0; i < (int)hdr.regionCount; i++) {
            const Mp6SavestateRegion *fr = &fileRegions[i];
            if (fr->size == 0) {
                fprintf(stderr, "[SAVESTATE] refusing: region %d (%.*s) has zero size\n",
                        i, (int)sizeof(fr->name), fr->name);
                rc = MP6_SAVESTATE_ERR_FORMAT;
                goto done;
            }
            sum += fr->size;
            if (fr->kind == MP6_SS_REGION_CORO) {
                void *slotAddr = mp6_coro_slot_addr((int)fr->index);
                coroSeen = 1;
                if (slotAddr == NULL ||
                    (uint64_t)(uintptr_t)slotAddr != fr->addr ||
                    fr->size != (uint64_t)mp6_coro_slot_size()) {
                    fprintf(stderr, "[SAVESTATE] refusing: coro region %d (slot %u) does not "
                                    "match this process's pool layout\n", i, fr->index);
                    rc = MP6_SAVESTATE_ERR_LAYOUT_MISMATCH;
                    goto done;
                }
                continue;
            }
            if (coroSeen) {
                /* collect emits every non-CORO region before the coro slots;
                 * a non-CORO entry after one is not a table we wrote. */
                fprintf(stderr, "[SAVESTATE] refusing: region table order is not ours\n");
                rc = MP6_SAVESTATE_ERR_FORMAT;
                goto done;
            }
            /* Advance to this process's next non-CORO expected region. */
            while (e < nExpect && expect[e].kind == MP6_SS_REGION_CORO) {
                e++;
            }
            if (e >= nExpect ||
                fr->kind != expect[e].kind ||
                fr->size != expect[e].size ||
                (fr->kind != MP6_SS_REGION_ARAM && fr->addr != expect[e].addr)) {
                fprintf(stderr,
                        "[SAVESTATE] refusing: region %d (%.*s) does not match this build's "
                        "layout (file kind=%u addr=%llx size=%llu vs live kind=%u addr=%llx size=%llu)\n",
                        i, (int)sizeof(fr->name), fr->name,
                        fr->kind, (unsigned long long)fr->addr, (unsigned long long)fr->size,
                        e < nExpect ? expect[e].kind : 0,
                        e < nExpect ? (unsigned long long)expect[e].addr : 0ull,
                        e < nExpect ? (unsigned long long)expect[e].size : 0ull);
                rc = MP6_SAVESTATE_ERR_LAYOUT_MISMATCH;
                goto done;
            }
            e++;
        }
        /* Every live non-CORO region must have been consumed -- a file with
         * FEWER image sections than this binary would otherwise partially
         * restore the image. */
        while (e < nExpect && expect[e].kind == MP6_SS_REGION_CORO) {
            e++; /* the live process's own in-use coro slots are not required of the file */
        }
        if (e != nExpect) {
            fprintf(stderr, "[SAVESTATE] refusing: state file covers fewer regions than this build\n");
            rc = MP6_SAVESTATE_ERR_LAYOUT_MISMATCH;
            goto done;
        }
        if (sum != hdr.rawBytes) {
            fprintf(stderr, "[SAVESTATE] refusing: region sizes sum to %llu but header says %llu\n",
                    (unsigned long long)sum, (unsigned long long)hdr.rawBytes);
            rc = MP6_SAVESTATE_ERR_FORMAT;
            goto done;
        }
    }

    /* the audio shadow is header data no other check covers --
     * clamp its counts before anything iterates them. Capture clamps on
     * write, so an out-of-range value here can only mean corruption. */
    if (hdr.audio.chanCount < 0 || hdr.audio.chanCount > MP6_SS_AUDIO_MAX_CHAN ||
        hdr.audio.groupCount < 0 || hdr.audio.groupCount > MP6_SS_AUDIO_MAX_GROUPS) {
        fprintf(stderr, "[SAVESTATE] refusing: audio shadow counts out of range (chan=%d group=%d)\n",
                (int)hdr.audio.chanCount, (int)hdr.audio.groupCount);
        rc = MP6_SAVESTATE_ERR_FORMAT;
        goto done;
    }

    /* Decompress everything into scratch FIRST. Nothing below this point
     * touches live memory until the whole payload has been proven intact --
     * that is what makes a corrupt file a clean error instead of a
     * half-restored process.
     *
     * the single-shot inflate hands rawBytes to zlib's 32-bit
     * avail_out, so the guard must be UINT32_MAX -- the earlier >SIZE_MAX
     * test was vacuous on win64 and a >4GB state would have truncated the
     * window and failed with a misleading ERR_FORMAT. Latent today
     * (~300MB), but the failure it names is a size threshold, so name it. */
    if (hdr.rawBytes == 0 || hdr.rawBytes > 0xFFFFFFFFull) {
        fprintf(stderr, "[SAVESTATE] refusing: rawBytes %llu exceeds the 4GB single-shot "
                        "inflate limit\n",
                (unsigned long long)hdr.rawBytes);
        rc = MP6_SAVESTATE_ERR_FORMAT;
        goto done;
    }
    raw = (unsigned char *)malloc((size_t)hdr.rawBytes);
    inBuf = (unsigned char *)malloc(kChunk);
    if (raw == NULL || inBuf == NULL) {
        rc = MP6_SAVESTATE_ERR_NOMEM;
        goto done;
    }
    memset(&zs, 0, sizeof(zs));
    if (inflateInit(&zs) != Z_OK) {
        rc = MP6_SAVESTATE_ERR_NOMEM;
        goto done;
    }
    zInit = 1;
    zs.next_out = raw;
    zs.avail_out = (uInt)hdr.rawBytes;
    for (;;) {
        size_t got = fread(inBuf, 1, kChunk, f);
        int zr;
        if (got == 0) {
            rc = MP6_SAVESTATE_ERR_FORMAT; /* ran out of input before Z_STREAM_END */
            goto done;
        }
        zs.next_in = inBuf;
        zs.avail_in = (uInt)got;
        zr = inflate(&zs, Z_NO_FLUSH);
        if (zr == Z_STREAM_END) {
            break;
        }
        if (zr != Z_OK) {
            rc = MP6_SAVESTATE_ERR_FORMAT;
            goto done;
        }
    }
    if (zs.total_out != hdr.rawBytes) {
        rc = MP6_SAVESTATE_ERR_FORMAT;
        goto done;
    }

    /* Commit. From here on there is no failure path -- every destination
     * was validated above, and the source is fully materialized. */
    /* Latch every host-owned pointer we will need DURING the commit loop,
     * BEFORE the loop starts.
     *
     * This is not defensive style, it is required: the loop restores the
     * image's .bss early on, and g_fakeAram (platform/null/shims_manual.c)
     * lives there. Querying the ARAM buffer from inside the loop therefore
     * returns whatever the .bss restore just installed -- the CAPTURING
     * process's heap pointer -- and the memcpy writes 16 MB through it.
     * (Observed exactly that way: an access violation in memcpy at this
     * line, writing a foreign heap address.) Anything else this loop ever
     * needs from restorable memory must be latched here too. */
    {
        size_t latchedAramSize = 0;
        void *latchedAram = mp6_aram_savestate_buffer(&latchedAramSize);
        /* the tick BUDGET is a host run-parameter, not game
         * state -- it describes how long THIS invocation was asked to run
         * (a CLI arg, or "unlimited" for a double-click session). It lives
         * in restored .data, so without this latch a restore imports the
         * CAPTURING run's budget: an interactive session that loads a
         * scripted 4000-tick capture silently exits mid-play when the
         * rewound counter re-reaches 4000, and a scripted gate run that
         * loads an interactive capture inherits unlimited=1 and never
         * honors its budget. mp6_tick_count itself is deliberately NOT
         * latched -- rewinding it is load-bearing for the replay levers
         * and for determinism. */
        int latchedMaxTicks = mp6_max_ticks;
        int latchedUnlimited = mp6_ticks_unlimited;

    /* free THIS process's widescreen native snapshots while the live
     * registry pointers are still valid -- the commit loop is about to
     * overwrite them with the capturing process's (foreign) pointers, after
     * which the memory is unreachable and leaks on every load. */
    mp6_widescreen_savestate_prerestore();

    off = 0;
    for (i = 0; i < (int)hdr.regionCount; i++) {
        if (fileRegions[i].kind == MP6_SS_REGION_ARAM) {
            /* ARAM is the ONE region whose base is legitimately not pinned:
             * it is a host calloc, not a fixed-address reservation. Its
             * recorded address is therefore ADVISORY (diagnostics only) and
             * the payload goes into whatever buffer THIS process allocated.
             * Size must agree exactly -- a differing size means a different
             * build's ARAM constant, which the build stamp should already
             * have rejected, so this is belt-and-braces. */
            if (latchedAram != NULL && latchedAramSize == (size_t)fileRegions[i].size) {
                memcpy(latchedAram, raw + off, latchedAramSize);
            } else {
                fprintf(stderr, "[SAVESTATE] WARNING: ARAM buffer unavailable or size "
                                "mismatch (live=%zu file=%llu) -- ARAM contents NOT restored\n",
                        latchedAramSize, (unsigned long long)fileRegions[i].size);
            }
        } else {
            memcpy((void *)(uintptr_t)fileRegions[i].addr, raw + off, (size_t)fileRegions[i].size);
        }
        off += fileRegions[i].size;
    }

    /* Re-derive host-side state that the commit loop just desynchronized.
     * Order is load-bearing -- see mp6_savestate.h. ARAM first because the
     * .bss restore above just clobbered g_fakeAram with the capturing
     * process's pointer, and anything that touches ARAM afterwards would
     * follow it. We hand back the LATCHED buffer (the one the loop actually
     * copied the restored bytes into), not a freshly allocated one -- an
     * allocate-a-new-one rehydrate would throw those bytes away and leave
     * ARAM zeroed while the restored residency table insisted it was full. */
    mp6_aram_savestate_rehydrate(latchedAram);

    /* put the RUNNING invocation's tick budget back (latched above). */
    mp6_max_ticks = latchedMaxTicks;
    mp6_ticks_unlimited = latchedUnlimited;
    }

    mp6_dvd_savestate_rehydrate();

#ifndef MP6_HEADLESS_BUILD
    /* FINDING #1 (savestate-x1): drop the Unlocked FPS interpolation state on
     * restore. frame_interp.c's pacing statics are carved out of the image (so
     * the commit loop above did NOT clobber them), but the retained N-1/N model
     * snapshots still describe PRE-restore frames -- clear them so the first
     * post-restore window starts clean instead of interpolating across the
     * state discontinuity. Windowed build only (frame_interp.c is aurora-only;
     * nothing to reset headless -- the model module never replays there). */
    {
        extern void mp6_fi_savestate_reset(void);
        mp6_fi_savestate_reset();
    }
#endif

    /* rebuild the widescreen native snapshots from the file's blob
     * (offset = header + table + deflate stream; hdr.compressedBytes is the
     * key -- its first real consumer). Every entry the blob cannot cover
     * fails soft to the apply early-out: frozen geometry, never corruption
     * and never a foreign pointer. */
    {
        long blobOff = (long)(sizeof(Mp6SavestateHeader)
                              + (size_t)hdr.regionCount * sizeof(Mp6SavestateRegion)
                              + (size_t)hdr.compressedBytes);
        void *wsBlob = NULL;
        size_t wsSize = (size_t)hdr.wsNativeBytes;
        if (wsSize > 0 && wsSize < (64u << 20) && fseek(f, blobOff, SEEK_SET) == 0) {
            wsBlob = malloc(wsSize);
            if (wsBlob != NULL && fread(wsBlob, 1, wsSize, f) != wsSize) {
                free(wsBlob);
                wsBlob = NULL;
            }
        }
        /* Called even with a NULL blob: it must still clear the foreign
         * pointers the image restore just installed. */
        mp6_widescreen_savestate_apply_natives(wsBlob, wsBlob ? wsSize : 0);
        free(wsBlob);
    }
    /* Audio LAST: re-establishing a stream issues DVD reads (msmStreamPlay ->
     * decode_substream -> path resolution -> the FST), so it depends on the
     * DVD layer above already being rehydrated. */
    mp6_msm_savestate_apply(&hdr.audio);

    g_wasRestored = 1;
    printf("[SAVESTATE] restored %s: %d regions, %.1f MB (rehydrated aram/dvd/widescreen)\n",
           path, (int)hdr.regionCount, (double)hdr.rawBytes / (1024.0 * 1024.0));
    fflush(stdout);

done:
    if (zInit) {
        inflateEnd(&zs);
    }
    free(raw);
    free(inBuf);
    if (f) {
        fclose(f);
    }
    return rc;
}

/* ==================================================================
 * Frame-boundary driver
 * ==================================================================
 * NOTE ON THIS FILE'S OWN STATICS. savestate.c is force-included with
 * mp6_host_section.h, so everything below lives in the host-owned carve-out
 * section and is NOT itself captured or restored. That is load-bearing, not
 * incidental: g_pending is set by the hotkey handler and consumed here, so
 * if it were part of the captured image it would be restored along with
 * everything else -- and a state captured while a request was in flight
 * would re-trigger that same request on every load, forever. Carving this
 * file out makes the request flag belong to the RUNNING process, which is
 * the only process it can meaningfully refer to.
 */
enum { MP6_SS_PENDING_NONE = 0, MP6_SS_PENDING_SAVE, MP6_SS_PENDING_LOAD };
static int g_pending;
static int g_tickLeversParsed;   /* -1/0/1 lazy-parse, matching this port's env-lever house style */
static long g_saveAtTick = -1;
static long g_loadAtTick = -1;
/* Fire-once latches for the scripted levers. REQUIRED, not defensive: a
 * restore rewinds mp6_tick_count to its captured value, so a bare
 * `mp6_tick_count == g_loadAtTick` test re-arms itself the moment the
 * replayed run counts back up to that tick -- an infinite restore loop
 * (observed, not theorized: the first version of this file hung exactly
 * this way). These latches live in the host-owned carve-out section along
 * with the rest of this file's statics, so a restore does NOT reset them --
 * which is precisely what makes them able to break the cycle. */
static int g_saveFired;
static int g_loadFired;
static char g_slotPath[512];
/* UI slot-request extension (mp6_savestate.h "Slot-file UI seam"): the
 * pending request's target path (empty = default slot path), and the
 * one-shot last-result pickup the in-game Save States page consumes. All
 * carved-out for the same reason g_pending is: they describe the RUNNING
 * process's UI conversation, which a restored image must not overwrite. */
static char g_requestPath[520];
static int g_lastResultValid;
static int g_lastResultWasSave;
static int g_lastResultCode;
static unsigned int g_uiGeneration;

/* The tick counter both build modes advance (platform/null/shims_manual.c),
 * used only by the scripted env levers below. */
extern long mp6_tick_count;

static const char *mp6_ss_slot_path(void)
{
    if (g_slotPath[0] == '\0') {
        const char *env = getenv("MP6_SAVESTATE_PATH");
        snprintf(g_slotPath, sizeof(g_slotPath), "%s",
                 (env && env[0]) ? env : "mp6_savestate.mp6state");
    }
    return g_slotPath;
}

void mp6_savestate_request_save(void) { mp6_savestate_request_save_path(NULL); }
void mp6_savestate_request_load(void) { mp6_savestate_request_load_path(NULL); }

void mp6_savestate_request_save_path(const char *path)
{
    snprintf(g_requestPath, sizeof(g_requestPath), "%s", (path && path[0]) ? path : "");
    g_pending = MP6_SS_PENDING_SAVE;
}

void mp6_savestate_request_load_path(const char *path)
{
    snprintf(g_requestPath, sizeof(g_requestPath), "%s", (path && path[0]) ? path : "");
    g_pending = MP6_SS_PENDING_LOAD;
}

void mp6_savestate_slot_file(int slot, char *buf, size_t n)
{
    const char *base = mp6_ss_slot_path();
    size_t len = strlen(base);
    const char *suffix = ".mp6state";
    size_t sufLen = strlen(suffix);
    if (len > sufLen && strcmp(base + len - sufLen, suffix) == 0) {
        snprintf(buf, n, "%.*s_slot%d%s", (int)(len - sufLen), base, slot, suffix);
    } else {
        snprintf(buf, n, "%s_slot%d", base, slot);
    }
}

int mp6_savestate_probe(const char *path)
{
    Mp6SavestateHeader hdr;
    FILE *f;
    if (path == NULL) {
        return MP6_SAVESTATE_ERR_IO;
    }
    f = fopen(path, "rb");
    if (f == NULL) {
        return MP6_SAVESTATE_ERR_IO;
    }
    if (fread(&hdr, sizeof(hdr), 1, f) != 1) {
        fclose(f);
        return MP6_SAVESTATE_ERR_FORMAT;
    }
    fclose(f);
    if (hdr.magic != MP6_SAVESTATE_MAGIC || hdr.version != MP6_SAVESTATE_VERSION) {
        return MP6_SAVESTATE_ERR_FORMAT;
    }
    if (strncmp(hdr.buildStamp, mp6_link_stamp, sizeof(hdr.buildStamp)) != 0) {
        return MP6_SAVESTATE_ERR_BINARY_MISMATCH;
    }
    return MP6_SAVESTATE_OK;
}

int mp6_savestate_take_last_result(int *wasSave, int *result)
{
    if (!g_lastResultValid) {
        return 0;
    }
    g_lastResultValid = 0;
    if (wasSave) *wasSave = g_lastResultWasSave;
    if (result) *result = g_lastResultCode;
    return 1;
}

unsigned int mp6_savestate_ui_generation(void) { return g_uiGeneration; }

/* parse a tick lever strictly, or refuse LOUDLY and stay
 * unarmed. Bare strtol let "3OO" parse as 3 and a fully non-numeric value
 * parse as 0 -- and 0 passes the >=0 arming test, capturing at the first
 * tick, which (save and load sharing one slot path) could overwrite the
 * very state file the user was about to load. Fail-closed means a typo
 * must disable the lever, not fire it somewhere surprising. */
static long mp6_ss_parse_tick_env(const char *name)
{
    const char *v = getenv(name);
    char *end = NULL;
    long parsed;

    if (v == NULL || v[0] == '\0') {
        return -1;
    }
    parsed = strtol(v, &end, 10);
    if (end == v || *end != '\0' || parsed < 0) {
        fprintf(stderr, "[SAVESTATE] %s=\"%s\" is not a valid tick number -- lever DISABLED "
                        "(a mis-parse must not fire at a surprise tick)\n", name, v);
        fflush(stderr);
        return -1;
    }
    return parsed;
}

void mp6_savestate_tick(void)
{
    int action;

    if (!g_tickLeversParsed) {
        g_saveAtTick = mp6_ss_parse_tick_env("MP6_SAVESTATE_SAVE_AT_TICK");
        g_loadAtTick = mp6_ss_parse_tick_env("MP6_SAVESTATE_LOAD_AT_TICK");
        g_tickLeversParsed = 1;
    }

    /* Scripted levers (the regression gate uses these -- they work in the
     * headless build too, where there is no window to press a key in).
     * only arm a lever when no request is already queued --
     * the levers used to overwrite g_pending unconditionally, silently
     * discarding an F5/F8 the user pressed on the same tick. The >= trigger
     * plus the fire-once latch means a deferred lever simply fires on the
     * next tick instead. */
    if (g_pending == MP6_SS_PENDING_NONE) {
        if (!g_saveFired && g_saveAtTick >= 0 && mp6_tick_count >= g_saveAtTick) {
            g_saveFired = 1;
            g_pending = MP6_SS_PENDING_SAVE;
        } else if (!g_loadFired && g_loadAtTick >= 0 && mp6_tick_count >= g_loadAtTick) {
            g_loadFired = 1;
            g_pending = MP6_SS_PENDING_LOAD;
        }
    }

    if (g_pending == MP6_SS_PENDING_NONE) {
        return;
    }
    action = g_pending;
    g_pending = MP6_SS_PENDING_NONE; /* cleared BEFORE acting: a failing
                                      * request must not retry every tick */

    {
        /* Consume the per-request target path (UI slot requests); empty =
         * the default slot path, exactly the pre-slot behavior. Latched
         * into a local BEFORE acting so a restore (which does not touch
         * these carved-out statics anyway) can never confuse it. */
        const char *path = g_requestPath[0] ? g_requestPath : mp6_ss_slot_path();
        int r;
        if (action == MP6_SS_PENDING_SAVE) {
            r = mp6_savestate_capture(path);
            if (r != MP6_SAVESTATE_OK) {
                fprintf(stderr, "[SAVESTATE] save failed: %s\n", mp6_savestate_strerror(r));
                fflush(stderr);
            }
        } else {
            r = mp6_savestate_restore(path);
            if (r != MP6_SAVESTATE_OK) {
                fprintf(stderr, "[SAVESTATE] load failed: %s\n", mp6_savestate_strerror(r));
                fflush(stderr);
            }
        }
        g_requestPath[0] = '\0';
        g_lastResultWasSave = (action == MP6_SS_PENDING_SAVE);
        g_lastResultCode = r;
        g_lastResultValid = 1;
        g_uiGeneration++;
    }
}
